mybb/mybb

- archive/global.php
- global.php
- inc/languages/english/global.lang.php
- install/resources/settings.xml
Fix #1341 Closed board message should load language string, fallback to custom reason if set.
> Fix #1341 Closed board message should load language string, fallback to custom reason if set.

- admin/inc/class_form.php
- admin/inc/class_page.php
- admin/jscripts/codemirror/theme/mybb.css
- admin/modules/style/templates.php
- admin/modules/style/themes.php
- admin/styles/default/main.css
Allows users to search CodeMirror content with browser by introducing the `viewportMargin: Infinity` option:
https://github.com/mybb/mybb/issues/1592
Ensures that the CodeMirror is always max. 100% width:
https://github.com/mybb/mybb/issues/1555
Also fixed tabbing issue (2 spaces were inserted instead of a tab due to outdated CodeMirror option usage) and a small typo in comment.
> Fix #1592 and #1555

- inc/functions.php
When a future timestamp is displayed in relative format, it would always be displayed in minutes. This fixes the problem and allows future timestamps to be displayed in minutes, hours and minutes, or as a normal date/time depending on how close it is to the current time.
Corresponding Thread in the forums: http://community.mybb.com/thread-166148.html
> Fix the display of future timestamps in "relative" mode

- inc/db_mysql.php
- inc/db_mysqli.php
- inc/db_pgsql.php
- inc/db_sqlite.php
- inc/functions.php
Define `$usergroup` as an array just in case there is nothing to return
to avoid PHP warnings.
https://github.com/mybb/mybb/issues/1756
> Fix #1756 missing array definition

- admin/jscripts/peeker.js
- admin/modules/config/profile_fields.php
- admin/modules/config/settings.php
- install/resources/settings.xml
Adds a possibilty to nest the peekers (so marking as an enhancement).
Fixes a bug where inputs without `id` attribute (like
groupselects/forumselects) couldn't have peekers for some unknown reason (`id` required but not used by/for anything).
Adds lots of missing settings peekers and groups them for having less
code to execute.
Moves some settings to other more proper groups (will be done
automatically by upgrade, right?).
https://github.com/mybb/mybb/issues/1325
> Fix #1325 add missing setting peekers

- inc/datahandlers/user.php
Fixes a possible buggy behavior after user deletion caused by the lack
of record deletion from `groupleaders` table when the whole account is
pruned.
https://github.com/mybb/mybb/issues/1818
Also removed some other forgotten stuff (3 things are still missing but
I'll open a new issue for that).
> Fix #1818 users not removed from groupleaders table

- install/resources/upgrade32.php
- install/upgrade.php
Moved the cookie unset code to avoid headers already sent warnings.
Added forgotten `$plugins` globalization to the `upgradedone()` function
to prevent `add_hook()` error.
https://github.com/mybb/mybb/issues/1811
> Fix #1811 upgrade issues

- admin/inc/functions_themes.php
- inc/functions.php
Fix installation/error caused by `$plugins->run_hook()` usage without
access to `$plugins` by checking if the object exists. I think it's
better than defining `$plugins` in several files.
https://github.com/mybb/mybb/issues/1830
> Fix #1830 installation/upgrade error

- install/resources/mybb_theme.xml
Checkboxes in private_quickreply have a space before their label
contents. private_send_tracking was missing a space and so the label
didn’t align with the others. This commit adds a space to fix the
problem.
> Add space for consistency in PM quickreply

- inc/languages/english/global.lang.php
- install/resources/mybb_theme.xml
Add filename and filesize into thumbnail title for images. 
It could be a part of #1583 . If you dont like this PR, just reject this. I applied it into my board, so I made a PR.
> Attachment improvement - add filename+filesize

- showthread.php
Fix #1210 soft deleted posts with showthread.php?pid=x#pidx
I'm unsure why `$visibleonly` and `$visibleonly2` weren't set in the core for normal users?
https://github.com/Sama34/mybb/blob/fix-1210/showthread.php#L744
> Fix #1210 soft deleted posts with showthread.php?pid=x#pidx 2

- admin/index.php
- admin/modules/home/preferences.php
- install/resources/mysql_db_tables.php
- install/resources/pgsql_db_tables.php
- install/resources/sqlite_db_tables.php
- install/resources/upgrade32.php
- install/resources/upgrade33.php
Fix #1840 Upgrade to 1.8.4 fails with SQLite
> Fix #1840 Upgrade to 1.8.4 fails with SQLite

- inc/datahandlers/warnings.php
Changes empty string assignments to `0` for 2 variables that are
supposed to be integers.
Removes some unnecessary escaping from variables which are always clean
(taken from database).
https://github.com/mybb/mybb/issues/1831
> Fix #1831 strict mode SQL errors, redundant escaping

- member.php
Added missing closing `]` to required fields selectors so that the rest
of the validator doesn't break.
https://github.com/mybb/mybb/issues/1930
> Fix #1930 typo in validation selectors

- admin/modules/config/smilies.php
As the title says, they're unnecessary there.
https://github.com/mybb/mybb/issues/1953
> Fix #1953 mass smilie edit - duplicate HTML entities escape

- admin/modules/config/smilies.php
Adds missing `\n` changes when saving multiline smilies through Mass Edit.
https://github.com/mybb/mybb/issues/1975
> Fix #1975 missing \n code in mass smilie edit

- inc/class_parser.php
Reverts the check to a correct one so that URLs are shortened by
default.
Could be merged into 1.8.5 since it's very simple to check. @JN-Jones
@ATofighi
https://github.com/mybb/mybb/issues/1995
> Fix #1995 URLs not shortened at all

- calendar.php
The '$event_errors' variable was cleared for no reason right before outputting the template, therefore deleting the errors.
https://github.com/mybb/mybb/issues/2001
> Fix #2001 Calendar does not show errors when adding events

- inc/db_mysql.php
- inc/db_mysqli.php
This only affected MySQL and MySQLi.
SQLite implementation already specifies tables only.
PostgreSQL doesn't include the views in information_schema.tables anyway.
> Fix #1913 Database export should ignore views

- inc/languages/english/polls.lang.php
- polls.php
Throws an eror if someone tries to enter `||~|~||` in one of the poll
options.
https://github.com/mybb/mybb/issues/1964
> Fix #1964 ||~|~|| sequence shouldn't be used in poll options

- private.php
Fixes #1912
Tested with umlauts (ä, ë, ï, ö, ü, ÿ), acutes (á, é, í, ó, ú, ý), graves (à, è, ì, ò, ù, ỳ), French Ç, Spanish Ñ, Polish Ł, German ß, Icelandic/Old English Ð and Þ and the letters Æ and Œ. Other letters should work too.
> Fixes #1912 PM download umlaut problems

- newreply.php
Fix for Issue #907 
The posthandler action is used to determine the mode of validation of post subjects. When saving a reply, it is set to "post". When previewing a reply, it is currently not set at all.
Simply setting the action to "post" fixes the validation of subjects for previews.
> Fix #907: Set posthandler-action for proper "subject" validation in preview

- admin/inc/class_page.php
- inc/functions.php
Fixes wrong checks for clickable smilies (both individual and global)
which didn't parse smilies in SCEditor at all while they should be only
hidden from the toolbar.
https://github.com/mybb/mybb/issues/1955
> Fix #1955 wrong SCEditor smilie checks

- private.php
If the `$bcc_recipients` array is empty, the `$bcc_form_val` should be an empty string.
Signed-off-by: Euan Torano <euantorano@gmail.com>
> Initialise $bcc_form_val to an empty string.

- inc/functions.php
Apparently neither "0" nor "false" get "my_date" to calculate the offset correctly so reverted it to an empty string and edited the doc block to reflect that behavior
As it's a leftover of #2026 I won't create a new issue for this.
> Fixes an issue I've introduced with #2026

- newreply.php
Previously, the beginning-of-string caret was not added to the start
of the regex, which caused other occurrences of "re" in the subject to
be stripped erroneously
(i.e. Sierra Madre: test will result in invalid RE: Sierra Madtest).
This commit adds the ^ character to the beginning of the regex, which
anchors the search to beginning-of-string.
Test successful with regexr. http://regexr.com/3bnsm
> (Fix #2168) Add start-of-string caret to RE: regex in newreply

- admin/modules/user/users.php
`language` was duplicated.
All other cases are already handled by the user datahandler
#2191
> Fixes #2191 Issue with user awaiting activation

- install/resources/mybb_theme.xml
Add missing title tag for search_results_posts_post
title="{$folder_label}" is missing in this template; in  search_results_threads_thread is here
> Fixes #2223 - Add missing title tag for search_results_posts_post

- inc/class_parser.php
The mentioned characters were disallowed for no apparaent reason.
https://github.com/mybb/mybb/issues/2232
> Fix #2232 URLs with & and () and without protocol not parsed

- install/resources/mybb_theme.xml
* Defined the desired CSS rule only for first child of tborder class.
* Changed the version number of css3.css to 1807
> Fixes #2237 Round corners in child tables inconsistent

- admin/modules/tools/system_health.php
> Fixes #2274 - UTF8 Conversion doesn't work for languages that comma != `,`

- install/resources/mybb_theme.xml
* removed unnecessary ```</a>```
* changed version to 1807
> Fixes #2276 Redundant </a> in template "misc_whoposted_poster"

- install/resources/mybb_theme.xml
- Added missing ```</td>```
- Changed version to 1807
> Fixes #2288 Missing closing </td> in template report_error_nomodal

- admin/modules/config/settings.php
As the title says - it worked like radios since 1.6 - only one value was saved. Multiple selections are saved to database separated with a comma now. A bit hacky solution with a hidden field, but it works and I don't think there is anything simplier than that.
https://github.com/mybb/mybb/issues/1947
Also added some missing fields that shouldn't be used as a hidden captcha.
EDIT: and fixed 2 peeker regexes to check for a complete match rather than a partial match.
> Fix #1947 checkbox optionscode doesn't work

- admin/modules/user/users.php
- usercp.php
Forces all Gravatars to HTTPS and changes usercp.php
to remove the .jpg extension from its Gravatar URL because
that was inconsistent with the admin/modules/user/users.php
version and wasted characters.
Signed-off-by: Josh Harmon <me@joshharmon.me>
> (#2046) Force HTTPS Gravatar URLs + Consistent URLs

- editpost.php
- inc/datahandlers/post.php
- inc/functions.php
It makes the original prefix available regardless of permissions when editing a thread.
Fixes #2287
> Fixes #2287 Prefix - Staff Only = Uneditable

- inc/functions_forumlist.php
Fixes #2142
Subforums which are password protected won't show up in the lastpost info of the parent forum unless you have filled out the password.
> Fixes #2142 Hide "Last Post" for password-protected forums by default

- inc/functions.php
- added PHP7's CSPRNGs
- checking the `$crypto_strong` parameter of `openssl_random_pseudo_bytes()`
- `secure_seed_rng()` returns numbers in the widest possible scope (previously maximum set for 32-bit systems, now dependent on the system)
- sources reordered, according to https://github.com/paragonie/random_compat/blob/master/ERRATA.md
`secure_seed_rng()` can be relatively slower due to restructuring (~0.8-1.2x) and `my_rand()` 6-9x slower on PHP7 and 6-14x slower on older versions.
Related: #1815, #2292
> RNG rewrite

- inc/datahandlers/post.php
- inc/functions.php
Fixes one invalid `is_member()` negation, returns empty strings instead
of `false` for HTML code, shortens redundant code (`-1` returns always
`true` for `is_member()` and `get_user()` the current user - `$mybb->user` - if the UID
matches).
https://github.com/mybb/mybb/issues/2051
> Fix #2051 wrong is_member() negation

- inc/mailhandlers/php.php
`$config` is global var, it should not be used in method scope.
> Fix php mail handler regression

- usercp.php
Used the more proper `private.php` code instead of removing it completely, which may result in new users being confused about lack of folders in menu after visiting `usercp.php` directly.
https://github.com/mybb/mybb/issues/2057
> Better fix for #2057 - PM folders not translated

- inc/class_parser.php
Adds a `<br class="clear" />` at the end of the message. I don't think
it's the best solution, `::after` would be much better, but at least it
stops `align` from being overly annoying.
https://github.com/mybb/mybb/issues/2405
> Fix #2405 [img align=X] float not cleared

- admin/modules/forum/announcements.php
- admin/modules/user/banning.php
- admin/modules/user/mass_mail.php
- admin/modules/user/users.php
- calendar.php
- inc/functions.php
- modcp.php
- moderation.php
Related Thread on Forum: http://community.mybb.com/thread-165257.html
The target of this pull request was two-fold:
1. Respect the "$mybb->settings['timeformat']" value (set in Admin-CP) at all locations that display time or allow the input of time as text (and don't/can't use my_date for date/time formatting). This affects:
Admin-CP Forum Announcement creation/editing
Admin-CP User banning preset bantimes selectbox entries
Admin-CP Mass Mail creation/editing
Mod-CP Forum Announcement creation/editing
Delayed Moderation
2. Respect current user timezone and dst when entering date/time. This affects:
Admin-CP Mass Mail creation/editing
Mod-CP Forum Announcement creation/editing
Delayed Moderation (original reason for this pull request as mentioned in the corresponding thread)
(Admin-CP …
> Fix localized date time input

- admin/modules/tools/file_verification.php
Fixes #2065; will skip the install directory and the hello world plugin file if they don't exist.
> Fixes #2065 Check files returns /install missing

- admin/inc/class_form.php
- admin/modules/config/mod_tools.php
#2066 
This issue is not related to the mod tools itself but to the fact that we check `$selected` via `empty` where PHP interprets `0` as empty. This makes sure that `$selected` is really an empty array otherwise we check the proper value which allows to select rows with `$value == 0`.
> Fixes #2066 by altering the form class to allow "0" as selected value

- inc/datahandlers/login.php
- inc/datahandlers/user.php
- inc/functions_user.php
Fixes #2498
- removed hardcoded `md5()` pre-hashing,
- `salt_password()` marked as deprecated,
- `create_password_hash()` and `verify_user_password()` added with new hooks, accepting the user row and raw password,
- complete user row fetched on login attempt,
- `my_hash_equals()` added, performing comparison using `hash_equals()` on PHP >= 5.6 or custom implementation
Session keys comparison should be also rewritten to use `my_hash_equals()` in the future.
Proof-of-concept plugin taking advantage of those changes available at: https://github.com/Devilshakerz/mybb-dvzHash
> Create hookable functions for password hashing

- inc/languages/english/moderation.lang.php
Fixes #2497 - Missing lang string for "time" in moderation
> Fixes #2497 - Missing lang string for "time" in moderation

- install/resources/mybb_theme.xml
#2522 
I've also standardized onclick calls (some are called with an old-fashioned javascript: prefix, the majority don't so I've deleted the javascript: prefix where present).
Despite fixing the issue, I do believe onclick should be avoided and added to inline scripts where possible.
> Fix #2522 - Links executing JS functions should return false and point to javascript.void(0) instead of hashtags

- install/resources/settings.xml
SFS registration link was changed since they stopped anonymous registrations and requires to register in their forum first to get an API key.
> Update SFS registration link to get an API key

- install/resources/settings.xml
Fixes #2299 - Missing setting desctriptions in ACP
@JN-Jones @PaulBender @Destroy666x @dequeues 
I am not sure about these: setting in L around n. 217 and 1411
Please review it carefully, I will try my best to find them all and fix the missing descriptions.
> Fixes #2299 - Missing setting descriptions in ACP

- admin/inc/class_page.php
- install/resources/mybb_theme.xml
- jscripts/general.js
> #2464-related patches

- inc/db_mysql.php
- inc/db_mysqli.php
If you are using MariaDB 10.x.x the server version returned is always 5.5.5 with mysqli_get_server_info().
With this issue, you cannot use FULLTEXT search with MariaDB.
More info: http://php.net/manual/en/mysqli.get-server-info.php#118822
> Wrong MySQL version detected

- install/resources/mybb_theme.xml
> Fixes #2640 - Error notice (div.error) styling doesn't match to 1.8 

- admin/modules/home/index.php
- install/resources/language.lang.php
The version check in the admin control panel points to `https://mybb.com/downloads` if the version is out of date, but the valid URL is `https://mybb.com/download` (without the s).
Fixes #2668
> #2668 - Update download link to point to `/download`

- install/resources/mybb_theme.xml
#2663 Wrong link to announcements in ModCP announcement list
After fix:
> Fixes #2663 - Wrong link to announcements in ModCP announcement list

- inc/functions_online.php
Fixes #2371 
The problem was initially setting the action to `0`. When checked by the first `in_array`, the loop was exited as the non-strict comparison evaluated to true.
> Fixes #2371 Incorrect user activity when action is unset

- admin/modules/tools/mailerrors.php
- admin/modules/tools/maillogs.php
- admin/modules/tools/system_health.php
- admin/modules/tools/tasks.php
- admin/modules/user/group_promotions.php
- global.php
- inc/class_parser.php
- inc/functions.php
- inc/functions_post.php
- inc/languages/english/admin/global.lang.php
- inc/languages/english/global.lang.php
- install/resources/mybb_theme.xml
- modcp.php
- usercp.php
- warnings.php
Fixes #2382 
- Added a 'normal' format to the my_date function. This will fully format the date and time without using relative dating.
- Changed a few instances of date() to my_date().
- Changed attachment hover from relative to normal (fixes #2751).
- Changed a few dates from older 1.6 style to 1.8 style.
- Fixed issue with relative time in quoted post (fix from [here](https://community.mybb.com/thread-210659-post-1274718.html#pid1274718)).
- Changed PM subscription excerpt to use normal date format (fixes #2802).
> Fixes #2382 my_date - no time for non-relative $format

- admin/modules/user/groups.php
This was useful for me when I was editing or adding a usergroup. 
Before I was adding a test account to the groups to double check the username styles every time.
> Preview usergroup's username style via user-group settings

- calendar.php
- install/resources/mybb_theme.xml
Fixes #2543 
Will hide all month and week links outside of the valid date range (January 1901 - December 5 years from now).
> Fixes #2543 Hide invalid Calendar links

- forumdisplay.php
- inc/functions_post.php
- inc/languages/english/modcp.lang.php
- install/resources/mybb_theme.xml
- jscripts/inline_reports.js
- modcp.php
- search.php
Fixes #154
Implementation the same as inline moderation.
Additional changes:
- Use strict comparison for `my_strpos` as it ignores the first item in the list without it
- Change `error_noselected_reports` to be the correct description - never used when "the selected posts have already been marked read by another user"
- Change "posts" to "content" in other language strings
---
**This PR:**
- changes 1 language file
- changes 2 templates
- adds 1 new template
- adds 1 new `.js` file
> Fixes #154 Select All for Reports

- install/resources/mybb_theme.xml
- showthread.php
#2815 
This PR also fixes a styling issue with the postbit_deleted_member template, which contained an extra `</div>` causing the `#posts` container to finish earlier in Mozilla browsers. Quick replies were then appended after deleted posts.
> Fixes #2815

- install/resources/upgrade41.php
This PR Iterates through the moderator log and removes slashes. As decided in PR #2839.
> Remove slashes from moderator log during upgrade

- install/resources/mybb_theme.xml
#2092 
The PR also tidies up the edited templates' indentation.
Other templates found to have `$multipage` nested into a form:
- modcp_modqueue_attachments
- modcp_modqueue_posts
- modcp_modqueue_threads
I'm not sure where to place the multipage there honestly. To render it usable, it must go either before the table (shifting the table down a little bit) or after the form submit button. Suggestions are appreciated.
> Fixes #2092

- admin/modules/user/users.php
Fixes #2367
Use `format_avatar` in the ACP user list. I couldn't find any other obvious occurrences of avatars being used in the ACP, but please point them out if I've missed any.
> Fix #2367 - ACP not using format_avatar() for formatting avatars

- admin/modules/tools/recount_rebuild.php
Fixes #2865.
PostgreSQL doesn't use backtick characters to quote identifiers.
> Fix #2865 - SQL error with PostgreSQL when running reputation recount

- inc/class_plugins.php
Fixes #2614 
Rather than using `get_class`, use [`spl_object_hash`](http://php.net/manual/en/function.spl-object-hash.php):
> This function returns a unique identifier for the object. This id can be used as a hash key for storing objects, or for identifying an object, as long as the object is not destroyed. Once the object is destroyed, its hash may be reused for other objects.
> Fix #2614 - Hooks with same class method of different objects not being added

- moderation.php
#2817 
I kept it extremely simple by clearing the cookies when browsing to the split thread tool page; a more complex approach would be:
- subtract the selected posts with the ones going to be split in the new thread;
- delete them from the previous thread's cookie;
- add them to the new thread's cookie, generating one.
While this may be more correct, it also adds something I feel unnecessary. The split thread tool is meant to work on its own, it does not preselects any already-selected posts; therefore, checking posts before using this tool might as well not be intentional but by mistake.
> Fixes #2817

- contact.php
- member.php
This partially fixes #257 by using the `$return_email` parameter of `my_mail` when sending an email from the `Contact Us` page.
This replaces #2873
> Fix #257 - Change to SMTP mail composition to comply with standards

- install/resources/upgrade41.php
This PR:
- globalizes the `$db` and `$output` objects in `upgrade41_dbchanges2`, which uses them;
- restores some @dvz's changes introduced in #2850, which were then overwritten by #2489 and subsequent PRs.
> Added db object to 2nd function, restored slashes normalization by dvz

- admin/styles/default/modal.css
- install/resources/mybb_theme.xml
This PR restores the old z-index to the modal's overlay (CSS rule: `.blocker`) which was introduced with jQuery Modal 0.5.9, in order to display the overlay above anything else (such as SCEditor or other z-indexed items).
> Restored z-index for modal overlay

- jscripts/general.js
- jscripts/inline_moderation.js
- jscripts/inline_reports.js
- jscripts/post.js
- jscripts/thread.js
This PRs restores the MyBB-specific wrapping for the Cookies library which was updated within #2697. The previous state was not accounting for any of the options set in the ACP; therefore, cookies were set without any prefix, path, domain or secure flag.
> Restored Cookies wrapping to reflect MyBB's ACP options

- .gitignore
- composer.json
- composer.lock
- global.php
Fixes #2907 by adding a Composer configuration file and ammends the `.gitignore` to ignore the vendor directory.
Dependencies are set to be installed to the `inc/vendor` folder, with classes autoloaded following the PSR-4 standard from `inc/src`.
> #2907 - Add Composer configuration

- admin/inc/functions.php
Fixes #2929 by adding a fallback in the case that `array_column` isn’t defined.
> Fixes #2929 - add a fallback for `array_column`

- composer.json
- composer.lock
- inc/src/functions.php
Fixe #2920. This adds the `Illuminate\Container` package as a dependency, and also adds a new `inc/src/functions.php` file that contains funcitons under the `\MyBB\` namespace. These functions are incldued by the autolaoder automatically.
It defines a single function, which can be used to resolve classes or get the container instance:
```php
// Get an instance of the container
$container = \MyBB\app();
// Get an instance of a class with no contructor parameters
$instance = \MyBB\app('SomeClass');
// Get an instance of a class with a set of constructor parameters
$instance = \MyBB\app('SomeOtherClass', ['foo']);
```
> Fixes #2920 - adds the Laravel Container

- global.php
- inc/src/bootstrap.php
Move the composer autoloader to a boostrap file so the files that do not require global.php have access to the autoloader without having to load global.php
> Move composer autoloader to bootstrap file

- admin/admin.php
- composer.json
- composer.lock
- inc/src/Http/Controllers/AbstractController.php
- inc/src/Http/Controllers/Admin/AbstractController.php
- inc/src/Http/Controllers/Admin/ToolsController.php
- inc/src/bootstrap.php
- inc/views/admin/tools/php_info.twig
- inc/views/layouts/admin.twig
Fixes #2935 - this is a work in progress.
The main purpose of this PR is to track the ongoing progress of this effort. Other people contributing to this effort should submit pull requests against [the branch](https://github.com/mybb/mybb/tree/develop/1.10-admin-cp).
> Admin CP rewrite

- inc/views/base/warnings/view.twig
- inc/views/base/warnings/warn.twig
- inc/views/base/warnings/warning_row.twig
- inc/views/base/warnings/warnings.twig
- warnings.php
Working on #2972
This PR is for the warning system (warnings.php).
> Working on #2972 Template Conversion to Twig Format (warnings.php)

- modcp.php
PostgreSQL doesn't use the `!` operator
> modcp.php: use `l.fid <> 0` instead of `!l.fid`

- inc/views/base/sendthread/sendthread.twig
- sendthread.php
> Working on #2972 Template Conversion to Twig Format (sendthread.php)

- search.php
The entire latter half of `search.php` needs to be rewritten. Almost identical code is replicated in at least 6 places and the interaction between the code and the database is inconsistent as hell. One of these broken promises is what caused the distant failure of moderation "select all" on user thread lists (#2915). `getallids()` in `moderation.php` expects `search.php` to behave in a sane way wrt interacting with the `searchlog` table but it doesn't and therefore `search.php` is at fault for the issue.
Notably, although there aren't issues related to #2915 yet, there should be and will be eventually. Trying to mass moderate "recent threads" as well as "today's threads" will exhibit exactly the same failure until someone fixes `search.php` more thoroughly. I'm happy to do that since I …
> Added more duct-tape to search.php (fixes #2915)

- announcements.php
- inc/views/base/announcements/announcements.twig
`announcements.php` Twig conversion for #2972
> Announcements — For #2972

- calendar.php
- inc/views/base/calendar/addevent.twig
- inc/views/base/calendar/calendar.twig
- inc/views/base/calendar/calendar_select.twig
- inc/views/base/calendar/dayview.twig
- inc/views/base/calendar/editevent.twig
- inc/views/base/calendar/event.twig
- inc/views/base/calendar/event_row.twig
- inc/views/base/calendar/move.twig
- inc/views/base/calendar/weekview.twig
Working on #2972
This PR is for the calendar (calendar.php).
> Working on #2972 Template Conversion to Twig Format (calendar.php)

- search.php
This is the first step in fixing the inline moderation "select all" feature for thread lists. By changing the interaction between `search.php` and the database (`searchlog`) to behave consistently and as expected elsewhere in the codebase, "select all" moderation now works everywhere it can be used (check "View New Posts" and "View Today's Posts" for example -- both fixed).
At this point, I'm comfortable that inline "select all" works as expected everywhere that it is supposed to. I would like to refactor the code in `search.php` to reduce the horrible replication and general atomic wreckage but this is an enhancement and will happen later and with more care (possibly using an entirely new branch as suggested by @tommm).
As it is, all the bugs in inline thread moderation are fixed and …
> Fixes inline moderation "select all" in all scenarios (#2958 extends #2957)

- showthread.php
When a user try to go to the last post of a thread, if the last post is soft deleted a jgrowl error message will popup if usergroup can see deletion notice.
> Fixed jgrowl messagge error

- modcp.php
When you accidentally forget to enter a ban reason when banning a user, you'll end up in a blank modcp.php page.
The issue is caused by $errors not properly being defined as an array.
This PR fixes issue #2993
> Fixes #2993 - banning without ban reason results in blank page

- inc/class_parser.php
Before this change all of these URLs would not be parsed:
```
[list]
[*]https://mybb.com
[/list]
[b]https://mybb.com[/b]
MyBB [https://mybb.com]
```
The following function as they did before this change:
```
[url=https://mybb.com]MyBB[/url]
[url=https://mybb.com/about/]https://mybb.com[/url]
[url]https://mybb.com[/url]
```
My only concern is the efficiency of the new regex. Would it be better to only do this change?
```diff
-[\>\s\(\)]
+[\>\s\(\)\[]|(?:\[\*\])
```
Even though this would result in the `[b]https://mybb.com[/b]` continue to not be detected?
> Fix mycode_auto_url to detect links when adjacent to square bracket

- forumdisplay.php
- install/resources/mysql_db_tables.php
- install/resources/upgrade30.php
- install/resources/upgrade36.php
- moderation.php
- showthread.php
I used a regex search to find instances of "groups" in query string parameters and backtick them.
Unfortunately, I can't get MySQL 8 working on my WAMP stack for some reason so I'd appreciate it if someone else could test to see if this does indeed fix #2921 
Thanks :)
> Escaping keyword "groups" for MySQL 8 (#2921)

- forumdisplay.php
- install/resources/mysql_db_tables.php
- install/resources/upgrade30.php
- install/resources/upgrade36.php
- moderation.php
- showthread.php
Reverts mybb/mybb#2955
AFter further review, that patch breaks PostgreSQL support, as the `\`` character is not an escape character for column names and causes syntax errors.
This means we need to either check the DB engine in use, or we need to do this at the DB class level.
Either way, this issue will be pushed back to 1.8.16 rather than 1.8.16.
> Revert "Escaping keyword "groups" for MySQL 8 (#2921)"

- modcp.php
Fixes #2990 
The code in the current `feature` branch runs a query globally in the Mod CP if a user isn't a super moderator to see if they have any moderator access at all and sets up various variables (such as `$numreportedposts` which was causing the problem in #2990 itself). However, it only considers the user's UID and their primary usergroup (`$mybb->user['usergroup']`) and ignores any additional groups that may be configured when running this query.
I'm not sure if it was like that for a reason, so hopefully this patch doesn't break anything else - it really needs testing with some different permission setups to make sure it doesn't cause problems.
> Consider both primary and secondary groups for Moderator CP

- inc/class_custommoderation.php
Fixes #3006 by removing `"` around moderation tool ID in query. Should still work on both postgres and mysql.
> Fix #3006 - custom moderation tool SQL error on postgresql

- inc/languages/english/memberlist.lang.php
- inc/views/base/memberlist/memberlist.twig
- inc/views/base/memberlist/memberlist_row.twig
- inc/views/base/memberlist/search.twig
- memberlist.php
Working on #2972
This PR is for the member list (memberlist.php).
> Working on #2972 Template Conversion to Twig Format (memberlist.php)

- inc/views/base/managegroup/joinrequests.twig
- inc/views/base/managegroup/managegroup.twig
- managegroup.php
> Working on #2972 Template Conversion to Twig Format (managegroup.php)

- inc/views/base/report/report.twig
- inc/views/base/report/report_error_nomodal.twig
- inc/views/base/report/report_reasons.twig
- inc/views/base/report/report_thanks.twig
- report.php
**[Ready for testing]**
For #2972
**Templates:**
```diff
+ report -> report.twig
+ report_thanks -> report_thanks.twig
+ report_reasons -> report_reasons.twig
+ report_error_nomodal -> report_error_nomodal.twig
- report_error
- report_duplicate
- report_reason
```
> Reports — For #2972

- inc/views/base/portal/portal.twig
- inc/views/base/portal/portal_announcement.twig
- portal.php
#2972 for portal.php
This is still incomplete, I need #2988 merged before I can finish this.
> Working on #2972 Template Conversion to Twig Format (portal.php)

- readme.md
Fix the contributor link by using a static link.
Github prepends a link to relative urls (`https://github.com/mybb/mybb/blob/feature/`), the resulting final url 404s.
> fix contributor link

- inc/class_parser.php
This PR fixes #3066 by parsing videos before URLs. I have proof-checked the whole parser and to me the only two MyCodes affected by #2968 are images and videos; all the others should not require any URL to be parsed.
> Fixed embedded videos not working after #2968

- global.php
- inc/init.php
https://github.com/mybb/mybb/issues/3017
THIS_SCRIPT fallback shifted from ./global.php to ./inc/init.php
> Fixes #3017 - PHP 7 / undefined constant THIS_SCRIPT

- polls.php
Fixes #3083 
Mods can vote, view results and undo vote in a poll if they can view either soft deleted or unapproved threads.
> Fixes #3083 Users can vote in polls in soft deleted threads

- inc/functions.php
- misc.php
As Euan and I previously discussed in private inquiries, help documents should allow Javascript code to execute. This pull request removes my_strip_tags in-order to allow them.
> Remove my_strip_tags from affecting help documents

- global.php
- inc/views/base/header/quicksearch.twig
- inc/views/base/header/welcomeblock_guest.twig
- inc/views/base/header/welcomeblock_member.twig
- inc/views/base/partials/header.twig
Twigplates edited and fixed:
I wasn't sure about the following piece of code:
```php
// Load appropriate welcome block for the current logged in user
if ($mybb->user['uid'] != 0) {
// Format the welcome back message
$lang->welcome_back = $lang->sprintf($lang->welcome_back, build_profile_link(htmlspecialchars_uni($mybb->user['username']), $mybb->user['uid']), $lastvisit);
}
// Otherwise, we have a guest
else {
switch ($mybb->settings['username_method']) {
case 0:
$login_username = $lang->login_username;
break;
case 1:
$login_username = $lang->login_username1;
break;
case 2:
$login_username = $lang->login_username2;
break;
default:
$login_username = $lang->login_username;
break;
}
}
```
I have tried creating a new variable for …
> Working on #2972 Template Conversion to Twig Format (header)

- inc/class_parser.php
Fixes #3150 by adding the "s" modifer to the regexes in
mycode_auto_url() so that the initial part of the regexes matching HTML
links detects HTML links that run over multiple lines.
> Fixes #3150 - Nested links still possible for multiline [url] tags

- inc/functions_upload.php
- install/resources/settings.xml
- install/resources/upgrade43.php
This fixes:
#2844 Impossible To Allow Unlimited Maximum Avatar Upload Size
#2801 I can't set to 0 to disable some feature in AdminCP
Fixed fields:
- Max Uploaded Avatar Size
- Login Attempts Timeout
- Maximum Attachments Per Post
- Maximum Page Links in Pagination
- Maximum Number of Poll Options
Old reference PR:
#1915 Numeric fields - default values
> Fixes #2844 #2801 ACP Set '0 to disable' issue

- admin/inc/functions_themes.php
Attempt to fix #2137 
Preserve Stylesheet Disporder, remove unwanted process to reset disporder.
> Fixes #2137 Stylesheet order reset after importing a theme

- inc/datahandlers/user.php
Attempt to fix #3081 
Verify email before password.
> Fixes #3081 Empty Email Address can result in PHP Warning on user validation

- inc/class_language.php
This PR fixes #3113 by allowing `set_language` to use the board's default `bblanguage`.
> Fixes #3113 – Added default language to set_language()

- inc/views/base/usercp/avatar.twig
- usercp.php
Templates not converted, related to avatar and used in other templates:
- usercp_currentavatar
This PR also deletes `usercp_avatar_intermediate` hook.
> Working on #2972 Template Conversion to Twig Format (usercp_avatar)

- inc/functions.php
Fixes #3263 by casting the posticons cache as array to prevent the `foreach` to loop into a non-array if the posticons cache is empty (eg.: during partial installs or other odd configurations).
> Fixes #3263 – Missing array casting produces warning when posticons cache is empty

- install/resources/upgrade43.php
This PR fixes an error when upgrading from 1.8.15 to 1.8.16 caused by `field_exists` holding the field before the table, and not the other way round.
> Fixed swapped field/table in field_exists check

- contact.php
- editpost.php
- inc/class_captcha.php
- inc/class_error.php
- inc/functions.php
- inc/views/base/layouts/master.twig
- inc/views/base/misc/attachment_icon.twig
- inc/views/base/misc/captcha/hidden.twig
- inc/views/base/misc/captcha/post.twig
- inc/views/base/misc/captcha/register.twig
- inc/views/base/misc/changeuserbox.twig
- inc/views/base/misc/codebuttons.twig
- inc/views/base/misc/debugsummary.twig
- inc/views/base/misc/loginbox.twig
- inc/views/base/misc/php_warnings.twig
- inc/views/base/misc/redirect.twig
- member.php
- moderation.php
- newreply.php
- newthread.php
- polls.php
- sendthread.php
- showthread.php
Templates dropped because discontinued in 1.8 already:
- member_register_captcha_recaptcha
- post_captcha_recaptcha
> Working on #2972 Template Conversion to Twig Format (miscellaneous)

- inc/views/base/modcp/home.twig
- modcp.php
Note that `alt_trow()`, despite being available as a Twig extension, has not been added as it has been said that we were going for a pure CSS solution. The code was copied and modified from #3211 which should be updated accordingly if the aforementioned plan is correct.
> Working on #2972 Template Conversion to Twig Format (modcp)

- inc/functions_forumlist.php
- inc/views/base/forumbit/depth3.twig
- inc/views/base/forumbit/depth_1/cat.twig
- inc/views/base/forumbit/depth_1/last_post.twig
- inc/views/base/forumbit/depth_2/cat.twig
- inc/views/base/forumbit/depth_2/forum.twig
- inc/views/base/forumbit/subforums.twig
This is still untested 100%, but everything should be fine. `get_forum_unapproved` has been deprecated, as the only function using it was `build_forumbits` and I handled its routines in Twig instead. To ensure backwards compatibility, I have just added a `@deprecated` mark.
> Working on #2972 Template Conversion to Twig Format (forumbit)

- inc/views/base/header/welcomeblock_member.twig
The ACP link in the header currently points to `//index.php` due to `admin_dir` being undefined. This fixes it by using `mybb.config.admin_dir` instead.
> Fix ACP link in header

- inc/datahandlers/post.php
- install/resources/settings.xml
Covered field types for MySQL
Revised settings description.
> Fixes #3170 MySQL error with strict mode if message too long - Extended

- inc/functions.php
This PR fixes a little bug which prevents the loginlockout cookie to be cleared for guests.
> Moved cookie clearing out to guests

- global.php
Fixed #3345 by checking for cookies upon every page load in order to get rid of soft lockout cookies if using the modal to login.
> Fixes #3345 – Cookies not wiped if using the modal to log in

- showteam.php
Attempt to fix #3347 
Revising usage of short array syntax to keep backward compatibility with PHP < 5.4
> Fixes #3347 Revising usage of short array syntax in showteam.php

- admin/modules/config/settings.php
Attempt to fix #3359 
- Individual form generation per settings group against search
- Enabling form-wise settings `gid` value.
> Fixes #3359 Settings `gid` is blank in ACP settings search page

- admin/modules/config/badwords.php
- inc/class_parser.php
- inc/languages/english/admin/config_badwords.lang.php
Attempt to fix #3262 
Implemented effective usage of `*` and `+`
**Note: This is gonna break all the pre-defined bad word filters. Its is required to describe in release note to redefine bad word filters as per the new rule after applying this patch.**
> Fixes #3262 Bad word filter

- admin/modules/config/settings.php
- admin/modules/user/users.php
- inc/functions.php
- inc/functions_upload.php
- inc/languages/english/admin/config_settings.lang.php
- install/resources/settings.xml
- install/resources/upgrade12.php
- usercp.php
Attempt to fix #3192 
Added flexibility in defining and usage of avatar dimensions:
- Added validation while setting dimensions through ACP
- Modified ACP settings description to define both separator usage is acceptable.
- Modified width - height separation process (used `preg_split()` in place of `explode()`) to generate values when any of the two separators is used.
> Fixes #3192 Avatar dimension separator consistency

- inc/languages/english/global.lang.php
- inc/src/Twig/Extensions/CoreExtension.php
- inc/src/bootstrap.php
- inc/views/base/member/profile.twig
- inc/views/base/partials/time.twig
- inc/views/base/postbit/postbit.twig
- member.php
Part of #2976.
This PR adds the following:
- `my_date` filter:
```twig
{{ post.dateline|my_date('relative', 'offset', true) }}
```
This means that language strings are changed slightly, moving HTML into a partial template rather than a language string. Dates now also use the HTML 5 `<time>` element, with eh `datetime` attribute set and a `title` attribute that shows the date as a full string whether relative formatting is enabled or not.
I've tried to keep this functioning the same as the old `my_date`, but it was unclear to me what the different values of the `$ty` parameter to that function actually achieved...
- `my_number_format` filter:
```twig
{{ memprofile.threadnum|my_number_format }}
```
I plan to add other functions to this PR over this weekend.
> #2976 - add `my_date` filter and other useful twig functions

- admin/modules/style/templates.php
Fixes #3367.
I haven't tested this, but it should resolve the problem.
> Fixes #3367 - use table alias for title column

- admin/modules/tools/file_verification.php
Attempt to fix #3058
Using `file_get_contents( )` in place of `fetch_remote_file( )` to avoid accumulating unwanted garbage error page codes resulting to trigger the condition check `empty($file[0])` properly.
_Test result with 1.8.18 pre-release (where checksum file is missing remotely)_
Using `fetch_remote_file( )`:
Using `file_get_contents( )`:
> Fixes #3058 File Verification can wrongly parse mybb.com responses

- inc/functions.php
- inc/functions_archive.php
- inc/functions_forumlist.php
- inc/functions_search.php
- inc/functions_user.php
Fixes #3409 and fixes #3410.
Moves `my_hash_equals` to `inc/functions.php` and checks that `$mybb->cookies['forumpass'][$forum['fid']]` is set. I haven't tested this, but it should work.
> Fix #3409 by moving my_hash_equals

- usercp.php
Fixes #3397 Updated usercp.php on lines 585 and 603. Added htmlspecialchars_uni for $userfield to escape non-escaped options for checkboxes and radio buttons
> Fix #3397 - Custom Profile Fields - Certain characters not escaped

- archive/global.php
- archive/index.php
- global.php
- inc/functions.php
- inc/functions_archive.php
- inc/init.php
- inc/src/Twig/Extensions/CoreExtension.php
- inc/src/Utilities/BreadcrumbManager.php
- inc/src/bootstrap.php
- inc/views/base/partials/breadcrumb.twig
- inc/views/base/partials/header.twig
- phpunit.xml
- tests/Unit/Traits/LegacyCoreAwareTest.php
For #2972, adaptation of #3386.
This uses a Twig function to render the breadcrumb, and adds a new `BreadcrumbManager` class to manage breadcrumbs.
This isn't yet complete, as I plan to add a `multipage` Twig function as part of this PR to use in the breadcrumb template. It also doesn't do anything with the nav on the archive pages, which will need some work.
Pinging @Shade- since he worked on the original nav template conversion.
> Nav template conversion

- admin/modules/config/languages.php
fixes misstyping in language editor count() that causes warning on PHP7.2 when editing language with another one.
> fixes #3453 language editor misstyping in count() causes warning on PHP7.2

- admin/modules/config/settings.php
Fixes issue where ACP settings search option, has searched directly DB data (which is in english) without considering translation. Because of this, ACP options search feature didnt worked for any other language than english.
> fixes #3430 ACP settings search option hardcoded only for english language

- inc/src/Utilities/BreadcrumbManager.php
- tests/Unit/Utilities/BreadcrumbManagerTest.php
It looks like when I added the breadcrumb manager in a previous PR I forgot to include the unit tests. This PR adds the missing tests and patches the breadcrumb manager to remove any trailing slash on the board URL.
> BreadcrumbManager unit tests

- admin/inc/class_page.php
- install/resources/mybb_theme.xml
- install/resources/output.php
- jscripts/general.js
Fix #3241 
Changes to non-moderator functionality.
If "all" checkbox is used, item checkboxes are synchronized; after that it's unchecked when an item checkbox is unchecked (using `.trigger()` with extra parameter to distinguish the origin of this action).
> Fix #3241 .prop('checked') doesn't trigger change events

- inc/languages/english/modcp.lang.php
- inc/views/base/modcp/home.twig
The index page of the ModCP includes a 'Bans Ending Soon' section. If there are no bans ending soon this will incorrectly read **'There are currently no banned users.'** (when there _are_ users banned, just not any that have bans ending soon), I've added a language variable **$l['no_banned_soon']** and replaced the existing one in the template to add some clarity to this page.
> Improve language of bans ending soon in ModCP homepage

- admin/modules/config/plugins.php
- admin/modules/home/index.php
- inc/tasks/versioncheck.php
Fixes #3476 in the simplest way possible by just using `trim` on the returned contents.
As the plan is to rewrite the ACP in future versions (1.10+), I just wanted to take the easy route for now and we'll add better error management and logging for future releases.
> Fix #3476 - version check failing with blank lines in content

- global.php
- inc/languages/english/global.lang.php
- install/resources/mybb_theme.xml
> Fixes #3486 Missing Moderation Notices

- inc/src/Twig/Extensions/CoreExtension.php
- inc/src/Twig/Extensions/UrlExtension.php
- inc/src/Twig/ServiceProvider.php
This adds the required functions to generate URLs in Twig files, but doesn't update existing templates to make use of them.
This will be used by #3480.
> Twig extension to generate URLs.

- editpost.php
- forumdisplay.php
- inc/functions_post.php
- inc/languages/english/global.lang.php
- install/resources/settings.xml
- newreply.php
- showthread.php
- xmlhttp.php
> Fixes #3419 View Own Unapproved Threads / Posts

- .travis.yml
- composer.json
- composer.lock
- inc/src/functions.php
This updates some Composer dependencies that are not compatible with PHP 7.3. PHP 7.3 is also added to the Travis test matrix to catch any regressions.
It also adds a new `\MyBB\registerTwigExtension()` helper function that is handy when you have Twig extensions particular to certain pages.
> Fix compatibility with PHP 7.3

- css.php
- global.php
Fixes #3467 by loading all stylesheets loaded through `css.php` at once.
This does cause some issues with the stylesheet display order options, unfortunately. It could be possible to have the display order set in the following style:
- Sheet from `css.php`
- Sheet from cache
- Another sheet from cache
- ...
With this patch, the above would become:
- Sheet from cache
- Another sheet from cache
- All sheets from `css.php`, in order according to display order
We may also want to add some extra hooks into `css.php`, but I just wanted to whip up a first draft implementation to get more thoughts on the proposal.
> Fix #3467 - load all css.php stylesheets at once

- composer.json
- inc/datahandlers/login.php
- inc/datahandlers/user.php
- inc/functions_user.php
- inc/init.php
- inc/src/Application.php
- inc/src/Config/ServiceProvider.php
- inc/src/Hashing/HashManager.php
- inc/src/Hashing/MybbHasher.php
- inc/src/Hashing/ServiceProvider.php
- inc/src/Hashing/WrappableHasher.php
- install/resources/mysql_db_tables.php
- install/resources/pgsql_db_tables.php
- install/resources/sqlite_db_tables.php
> Resolve #3530 Modern password hashing

- README.md
Currently, the MyBB logo in the readme is not displayed, because it seems like the URL was changed from raw.github.com to raw.githubusercontent.com
> README: fix URL for MyBB logo

- inc/class_parser.php
Attempt to fix #3580 
Reverting word boundary to original might be the best optimal solution for now.
With the following known issues, as word boundary acts invert to the non word characters:
With a word filter `monk` to `pon`: `Monkey` will remain as is but `{monk}ey` will be affected resulting to `{pon}ey`.
If we try to filter `\()` with `no`:
`Hello \() MyBB` will not be changed, but `Hell\()o MyBB` will be affected resulting `Hellnoo MyBB`.
If we can live with those rare incidents this PR is good to go for now. If anyone has a better idea feel free to comment or push commits (for members) to PR.
> Fixes #3580 Oversensitive Word Filter

- admin/modules/tools/recount_rebuild.php
May be useful add a do_recount_rebuild hook in order to have directly included the post request check and the input page check, avoiding to rewrite them in the development of the plugin.
> New hook on recount_rebuild.php

- admin/modules/tools/recount_rebuild.php
Remove the double check of the per_page variable in order to set the default value one time.
> Unique check for per_page on recount_rebuild.php

- inc/class_datacache.php
The PHPDoc for `datacache::update()` wrongly states the content can only be a string when actually arrays and other types are supported. This PR corrects the documentation comment.
It also replaces `serialize` and `unserialize` with our `my_serialize()` and `my_unserialize()` functions for consistency with the rest of the code base. I don't foresee this causing any problems unless anybody is purposefully storing objects in the cache, which isn't something I've personally seen done before...
> Use `my_serialize` for cache and update PHPDoc

- inc/db_base.php
- inc/db_mysql.php
- inc/db_mysqli.php
- inc/db_pgsql.php
- inc/db_sqlite.php
Fixes #3647 - Incompatible arguments of DB_Base::modify_column() and DB_Base::rename_column() implementations
> Fix 3647 - add missing parameters to modify_column() and rename_column() in DB classes

- inc/functions_upload.php
Fixes #3656 
There are some other issues with editing posts, especially when JS is disabled. I'll open another issue regarding these.
> Fix #3656 - SQL Error on Post Update With Removed Attachment

- admin/modules/tools/recount_rebuild.php
Fixes #3651 - get the button's parent form rather than using the document's first form.
> Fix #3651 - use button's parent form

- inc/functions.php
The `debuglink` variable was missed in #3256 when the `debugsummary` template was converted to twig.
> Pass debuglink to template

- .github/FUNDING.yml
See the [documentation available here](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository). This will show a sponsor button on this repository to direct users towards OpenCollective.
> Add the new `funding.yml` file to show a sponsor button on GitHub

- install/index.php
#3530
`create_password` should be used in the installer as well. Currently without it `password_algorithm` is left blank meaning the admin user cannot login anywhere.
> #3530 Modern password hashing in installer

- xmlhttp.php
In https://github.com/mybb/mybb/commit/87f833ecd93a037c6a4c3904b692f93baec57380 the default behaviour of the XMLHTTP function `get_users` was changed from _starts with_ to _contains_ without any convincing reason or retrospective changes to core code to prevent regressions where this function is used.
The function is primarily used for autocompleting usernames in select boxes. The change to _contains_ would not normally be an issue as a selection of users are returned based on the search query, however, on forums with large numbers of members and common terms in usernames, it leads to users not being able to select a member from an user autocomplete box even when entering an exact username (as the results are returned A-Z).
A quick search reveals there is no core code that takes advantage …
> Revert get_users behaviour to starts with instead of contains

- global.php
- polls.php
Removes a query against the non-indexed `poll` column in the `threads` table in favor of get_thread() using the poll tid.
> Poll Voting Efficiency Fix

- admin/modules/forum/management.php
Fix errors of calling undefined `Form` objects in AdminCP > forum management since committed PR #3740 (fixes #3739).
Also add minimum values to those two numeric fields of `disporder`.
> Fix errors in pull #3740 calling undefined `Form` objects

- inc/views/base/showteam/showteam.twig
- showteam.php
- usercp.php
Fix errors on `showteam` when there are group leaders to display.
Fix errors on Forum Subscriptions page in UserCP with adding a missing `lastposteruid` variable.
These problems have been tracked in #3785. I'll try to fix other issues in separated PRs.
> Fix errors on showteam and usercp_forumsubscriptions

- inc/class_parser.php
- inc/languages/english/global.lang.php
Resolves #2440
Image paste from clipboard support added.
> Resolves #2440 Image paste from clipboard support

- forumdisplay.php
- inc/class_session.php
- index.php
- install/resources/mysql_db_tables.php
- install/resources/pgsql_db_tables.php
- install/resources/sqlite_db_tables.php
- install/resources/upgrade49.php
- online.php
- portal.php
- showthread.php
Resolves #3762.
To continue using the `mybb_sessions` table / `session` class for CSRF prevention tokens for guest users:
- a `mybb_sessions.isunique` column is created to indicate whether the session should be representative of a unique user and included in online counts/lists,
- the session system logic is modified to set old, conflicting sessions as not unique instead of having them deleted (resulting in additional `UPDATE` query for guest users in `session::update_session()`, which is called instead of `session::create_session()` as sessions continue with no disruption),
- online statistics sections are limited to unique sessions by extending general `SELECT` queries of `mybb_sessions` with a `isunique = 1` condition.
Alternatively to `isunique`-like column, `SELECT` queries could be …
> Resolve #3762 Purging guest sessions by IP address may invalidate anti-CSRF tokens between requests

- inc/class_session.php
Setting additional groups to empty can prevent the wrong users from potentially seeing privileged things, especially when using plugins that hook into the login process ([Mybb2fa](https://community.mybb.com/mods.php?action=view&pid=941) is affected by this).
Apologies if this isn't the correct format-- I'm new around these parts.
> Fix potential security issue in class_session.php

- inc/class_parser.php
Fixes #3828 by altering the `[font]` MyCode to only allow quotes at the start and end and to ensure the used quotes match each other.
Tested locally using the provided broken tag examples.
> Fix #3828 - Alter the [font] MyCode

- forumdisplay.php
Resolves #3829
Simplified construction of `t.visible` conditions. `$visibleonly` left out for (presumably) `posts` context.
> Resolve #3829 "Access Own Unapproved Threads / Posts" breaks thread filters & pagination

- jscripts/post.js
- jscripts/thread.js
Original issue: #3773.
Community thread: https://community.mybb.com/thread-224271.html
Fix multi-quoting when MyBBEditor is set to `null` for plain textarea input box pulled in https://github.com/mybb/mybb/pull/3774#issuecomment-561544068
Post the note here also, for quick reference:
> - `showthread` template includes `thread.js` only.
> - `newthread` & `newreply` templates include `post.js` only.
> In a default MyBB installation, the built-in SCEditor can only be enabled on full posting pages, i.e., `newthread` & `newreply` pages. Quick reply and vanilla text input box in newthread & newreply use `#message` as the input box's id. But it should be possible to enable quick reply to also use a WYSIWYG editor, and therefore `thread.js` & `post.js` should be able to both support where the …
> Extend #3774 quoting post from other threads not working

- forumdisplay.php
- index.php
- online.php
- portal.php
- showthread.php
Resolves #3762
Extends #3837
- DB interaction modified to count guests in a separate query with `COUNT(DISTINCT ip)`,
- `index.php` guest count query extended to return counts grouped by `location1` when `$mybb->settings['showforumviewing'] != 0` for the _N users browsing_ forum counts,
- `online.php`:
- more complex queries to filter guests by IP database engine version-dependent window functions, with a fallback for older versions (`MIN(sid)` only used to pick unique `sid` for each `{uid,ip}` pair when same timestamp is stored); no duplicate `{uid,ip}` pairs will be returned anymore (side effect in #3837), but spider and guest sessions associated with same IP may exclude each other in statistics
- fixed sorting for SQLite to show users first
Queries in this state rely on …
> Fix & optimize Who's Online queries

- install/resources/mybb_theme.xml
Resolves #3854.
MyBB Master Style version and the `post_attachments` template version both have been bumped to 1.8.23.
> Fix #3854 Unnecessary `</a>` in the `post_attachments` template

- inc/functions.php
Resolves #3906.
`peer_name` is needed when PHP connecting to certain sites, e.g. some of Cloudflare proxied ones, by `stream_socket_client()` using IP as host.
> Add `peer_name` to SSL context options when SSL verification is ignored.

- calendar.php
> Fix #3901 - calendar event name double encoded

- inc/views/base/partials/footer.twig
There was a mismatched closing HTML tag in the footer template - the opening tag was `<footer>` but the closing tag was `</div>`. Spotted by @yuliu and reported on Discord.
> Fix a mismatched HTML tag in the footer template.

- archive/index.php
- inc/functions.php
- inc/functions_archive.php
- inc/functions_forumlist.php
- inc/functions_search.php
Resolves #3422
- added function to check forum password validation status:
```php
function forum_password_validated($forum, $ignore_empty=false, $check_parents=false)
```
- weak comparisons (`==`, `empty()`) changed to identical (`===`) for no password check
- password verification comparison changed to use `my_hash_equals()`
- local optimizations
> Resolve #3422 Loose comparison used for forum passwords

- admin/modules/config/settings.php
Fixes #2056
When checking whether to add a full text index to the `threads` table the condition used `posts` - likely a copy & paste mistake.
> Fix #2056 - table name used for `is_fulltext` should be threads

- admin/modules/config/settings.php
- inc/functions.php
Resolves #4004.
Removed encoding conversion for user input.
Added a case insensitive version of mb accounted string search function `my_strpos()`, and changed to use it.
Added setting names and setting group names in the search.
...
IMO we don't need encoding conversion. The encoding of user input should be the one sent via HTTP HEADER or set in HTML's meta, which is the encoding property of the language used by current user. And the encoding of a language pack is expected to a same type encoding used by the database. Otherwise the board couldn't run properly. Anyway, if there's really something wrong with the encoding, it'll prevent the board from properly running first rather than the setting search function.
> Improve ACP settings search

- inc/db_mysql.php
- inc/db_mysqli.php
- inc/db_pgsql.php
- inc/functions.php
Resolves #3619
The purpose of these small bits of code seems to be moving the connection details to an array element when the details are specified in the top level so that afterwards `$connections[TYPE]` for `TYPE=read/write` is an array.
The issue has been that the whole of `$connections` is unset once the first one is processed which has prevented the multi connection code from working properly! 😢
Note it would have worked previously if specified by the user like this:
```php
$config['database']['read'][] = array(
'hostname' => 'localhost',
'username' => 'mybb',
'password' => 'password',
);
$config['database']['write'][] = array(
'hostname' => 'localhost',
'username' => 'mybb',
'password' => 'password',
);
```
but not like this:
```php
$config['database']['read'] = array(
'hostname' => …
```
> Fixes #3619 Bugs with advanced database configuration

- install/resources/mybb_theme.xml
Resolves #1427
Sum of selections of both `to` and `bcc` must not exceed `maxpmrecipients`.
When one input is taking the all of the allowance then the other is disabled (as cannot limit `maximumSelectionSize` to less than 1 with select2).
> Fixes #1427 Change max recipients

- jscripts/bbcodes_sceditor.js
Fixes #3889
Uses the suggestion by @JordanMussi in https://github.com/mybb/mybb/pull/3994
Some tests:
| SCEditor Source Mode Input | Source mode value after witching to WYSIWYG and back | Parsed by MyBB correctly? |
| ---- | ---- | ---- |
| ```[quote="euan's test"]double quote[/quote]``` | ```[quote="euan's test"]double quote[/quote]``` | Yes |
| ```[quote=euan]no quote[/quote]``` | ```[quote="euan"]no quote[/quote]``` | Yes |
| ```[quote="euan"]double quote[/quote]``` | ```[quote="euan"]double quote[/quote]``` | Yes |
| ```[quote='euan']single quote[/quote]``` | ```[quote="euan"]single quote[/quote]``` | Yes |
| ```[quote='euan says "hi"']single quote[/quote]``` | ```[quote='euan says "hi"']single quote[/quote]``` | Yes |
> Fix #3889 - quotes for usernames with quotes

- admin/modules/config/settings.php
- inc/class_error.php
- install/resources/settings.xml
Resolves #2962
This makes the following changes relating to how errors are displayed:
- Default the `Error Type Medium` setting to `Hide Errors and Warning`, meaning that by default full error details are not shown, which could leak potentially sensitive information such as database table prefixes.
- Prevent the `Error Type Medium` setting being hidden when the `Error Logging Medium` is `Neither`.
- When displaying an error, if the user is not an administrator change the text in the footer. For administrators, the text is:
> Please contact the MyBB Group for technical support.
For users, the text is:
> Please contact the site owner for technical support.
This should cut back on the number of emails we receive to `contact@` relating to an error on a site that we can do nothing about.
- For …
> #2962 error page display

- managegroup.php
no_users_selected was only being shown if `removeuser` was not an array.
If it was an empty array the error would not be shown and MyBB would continue as if nothing were wrong.
> managegroup do_manageusers: Fix check for whether any users are selected

- inc/functions_upload.php
The main problem was that in some (all?) cases, PHP upload
errors were being ignored. This was because the check for, and parsing
of, PHP upload errors occurred in the function `upload_attachment()`
which was sometimes not called on PHP upload errors due to the
following conditional in `add_attachments()`:
`if(!empty($FILE['name']) && !empty($FILE['type']))`
More specifically, `$FILE['type']` can be set to empty even though a
file with a valid file type was uploaded which exceeded the php.ini
setting `upload_max_filesize`, thus generating an `UPLOAD_ERR_INI_SIZE`
error.
This refactoring of the code ensures that the check for, and parsing of,
PHP upload errors is moved into a separate function, called up-front,
before that conditional, so that they cannot be ignored.
Resolves #3618
> Fixes #3618: Attachments not working properly in latest version

- inc/languages/english/messages.lang.php
- install/resources/mybb_theme.xml
Note: This PR removes the login form from the error_nopermission template and leaves a single "Login" button which takes you to the full login form.
Resolves #3560
> Resolves #3560 - Missing captcha v2 in "error_nopermission"

- admin/modules/config/settings.php
- inc/functions_search.php
- inc/languages/english/admin/config_settings.lang.php
- install/resources/upgrade50.php
Resolves #3526
`perform_search_mysql_ft` now behaves like `perform_search_mysql` by setting the hard coded minimum when `minsearchword` < 0
`minsearchword` has an enforced minimum when updating settings and using fulltext. This minimum is the one provided by the DB and uses the logic that used to be done on every fulltext search.
Upgrade script used to ensure minimum is enforced on upgrade so that searches aren't performed with a value less then the DB minimum.
> Fixes #3526 ft_min_word_len query every search

- inc/datahandlers/user.php
- install/index.php
- install/resources/upgrade50.php
- private.php
- usercp.php
> Fixes #4054 Default PM Folder Structure

- inc/class_stopforumspamchecker.php
Resolves #4100
Changing to HTTPS worked fine in my tests in 5.6 and 7.4 with PHP using cURL 7.58.0, using `stream_context_create` and `fsockopen`. I didn't even need to add the [`SNI_enabled`](https://www.php.net/manual/en/context.ssl.php#context.ssl.sni-enabled) parameter in the stream options.
I couldn't find any stats on cURL versions used by PHP installs to see about SNI support but since mybb.com is also behind Cloudflare using SNI the same problem is present for the upgrade check. So I think this change is safe to make.
> Fixes #4100 Insecure connection used for Stop Forum Spam API
