admin/modules/tools/maillogs.php, inc/functions.php, inc/functions_search.php, modcp.php, usercp.php
Fix #349 Perfomance problems on large sites with user logins
=> Fix #349 Perfomance problems on large sites with user logins

modcp.php
=> Fix #1730 right id column used

admin/inc/functions.php, admin/inc/functions_themes.php, admin/inc/functions_view_manager.php, admin/index.php, admin/modules/config/mod_tools.php, admin/modules/config/warning.php, admin/modules/forum/attachments.php, admin/modules/home/index.php, admin/modules/style/themes.php, admin/modules/tools/cache.php, admin/modules/tools/optimizedb.php, admin/modules/user/admin_permissions.php, admin/modules/user/mass_mail.php, admin/modules/user/users.php, forumdisplay.php, inc/cachehandlers/apc.php, inc/cachehandlers/eaccelerator.php, inc/class_datacache.php, inc/datahandlers/event.php, inc/datahandlers/pm.php, inc/functions.php, inc/functions_modcp.php, install/index.php, install/resources/upgrade12.php, install/resources/upgrade30.php, install/upgrade.php, moderation.php
=> WIP #1733 Update my_serialize not to support objects or resources

admin/modules/user/groups.php, inc/languages/english/admin/user_groups.lang.php, install/resources/mysql_db_tables.php, install/resources/pgsql_db_tables.php, install/resources/sqlite_db_tables.php, install/resources/upgrade32.php, install/resources/usergroups.xml, reputation.php
=> Feature #1586 Delete Reputation permission

install/upgrade.php
=> Fixes #1657 Upgrade script loads plugins.

polls.php
Fix #1726 $fid not defined in polls.php::L#584
=> Fix #1726 $fid not defined in polls.php::L#584

portal.php
Fix #1321 Multipage doesn't work if portal.php is renamed
=> Fix #1321 Multipage doesn't work if portal.php is renamed

admin/modules/user/banning.php, admin/modules/user/users.php, inc/languages/english/admin/user_users.lang.php
Improve #1354 "Moderator Options" time difference
=> Improve #1354 "Moderator Options" time difference

admin/inc/functions.php, install/index.php, install/upgrade.php
Fixes the Moderation permissions saving issue - haven't tested yet but
it should work.
https://github.com/mybb/mybb/issues/1735
Also adds missing column names to a variable. Not sure if it's even used
during installation/upgrade but I left it just in case.
=> Fix #1735 Moderation permissions saving issue

inc/functions_user.php, install/resources/mybb_theme.xml, jscripts/captcha.js, jscripts/question.js, jscripts/thread.js, member.php, xmlhttp.php
Fixes the validator after refreshing captcha/question.
https://github.com/mybb/mybb/issues/1454
Fixes `generate_question()` not considering old question which resulted
in failed refresh sometimes.
https://github.com/mybb/mybb/issues/1549
Cleans JS a bit.
EDIT: <S>don't merge it yet</s> as I'm fixing this 3rd validation problem too: http://community.mybb.com/thread-159193.html
=> Fix #1454 and #1549

install/index.php
Used `strrpos()` to find the last occurence of the folder and cleaned
some redundant stuff to simplify the code.
https://github.com/mybb/mybb/issues/1728
=> Fix #1728 last occurence of /install/

inc/class_parser.php
=> Fixes #1646 HTML entities not escaped in links when HTML is enabled

admin/modules/tools/spamlog.php
Fixes #1727
Also fixes some minor formatting issues, a bad ip address filter and deleted an extra output_footer.
=> Fixes #1727 No pagination on Spam Log

install/resources/upgrade32.php
Fixes #1681; setting needs to be updated on upgrade.
=> Fixes #1681 noCaptcha with MyBB

install/resources/mybb_theme.xml
=> Fixes #1762 Invalid subscribed forum icon code

admin/inc/class_table.php
Fix #1753 ID is set even when empty.
=> Fix #1753 ID is set even when empty.

inc/functions.php
=> Fixes #1704 Banned IPs not being blocked

inc/class_session.php, install/upgrade.php
=> Fixes #1770 Remove sessions from upgrade script

install/resources/mybb_theme.xml
Visual fix in postbit_gotopost - HTML
=> Visual fix in postbit_gotopost - HTML

forumdisplay.php
=> Fixes #1785 Unnecessary datecut param in forumdisplay.php

admin/index.php, inc/functions.php, install/index.php, install/resources/upgrade32.php
Makes the forced cookies work with `/` cookiepath for a forum in a
subfolder (and any other combination).
https://github.com/mybb/mybb/issues/1656
=> Fix #1656 finish forcing cookie to ACP dir

admin/index.php, inc/datahandlers/login.php
=> ACP uses loginhandler properly

admin/inc/class_page.php, admin/modules/config/smilies.php, inc/class_parser.php, inc/functions.php, misc.php
Changed `addslashes()` to `str_replace()` with only
Added missing `get_asset_url()` to some places (but still missing in
some other places in front-end, will create another issue for this) and missing `{theme}` replacement to ACP SCEditor smilies.
https://github.com/mybb/mybb/issues/1453
=> Finish fixing #1453 smilies breaking

admin/modules/tools/cache.php, inc/cachehandlers/apc.php, inc/cachehandlers/eaccelerator.php, inc/class_datacache.php, inc/functions.php
Fixes #1733
- Slightly increased limit
- Cache uses native functions
=> Fixes #1733 Update my_serialize not to support objects or resources

inc/languages/english/online.lang.php
Fixes 2 and removes 1 outdated online location links.
https://github.com/mybb/mybb/issues/1673
=> Fix #1673 wrong online location links

admin/modules/forum/attachments.php
Removed overwriting `$mybb->input` values
=> Fixes #1767

CONTRIBUTING.md
Fix #1827 Update CONTRIBUTING.md
=> Fix #1827 Update CONTRIBUTING.md

inc/class_parser.php
Fix #1835 Useless variable in class_parser.php
=> Fix #1835 Useless variable in class_parser.php

xmlhttp.php
=> Fixes #1740 - Board Online/Offline for xmlhttp.php

xmlhttp.php
=> Fixes #1844 Inline edit subject check

member.php, newreply.php, newthread.php
=> Fixes #1874 - Nocaptcha missing on newreply.php and newthread.php

inc/class_custommoderation.php, inc/class_moderation.php, moderation.php
Fix #1676 $fid in toggle_thread_softdelete
=> Fix #1676 $fid in toggle_thread_softdelete

admin/modules/user/groups.php
Fix #1876 Group leader admin logs inconsistencies
=> Fix #1876 Group leader admin logs inconsistencies

inc/datahandlers/post.php, inc/languages/english/datahandler_post.lang.php, newreply.php, newthread.php
=> fix: inline error for username taken (guest post/thread), refs #841

inc/languages/english/member.lang.php
=> Fixes #1888 "remaining" is missing from bannedbit in profiles

inc/class_custommoderation.php
=> Fixes #1882 Soft Delete option in custom mod tools doesn't work

inc/datahandlers/pm.php
Fix #1845 PM Verification Incorrect (ignore list)
=> Fix #1845 PM Verification Incorrect (ignore list)

inc/tasks/delayedmoderation.php
Fixes 2 typos in delayed moderation task.
https://github.com/mybb/mybb/issues/1891
=> Fix #1891 typos in delayed mdoeration task

contact.php
Limit the captcha to guests just like it's done in other pages
(sendthread, newreply, newthread)
https://github.com/mybb/mybb/issues/1901
=> Fix #1901 captcha in contact.php showing for everyone

install/resources/mybb_theme.xml, usercp.php
Move misplaced `<br />` to beginning of another template to avoid
duplicate.
https://github.com/mybb/mybb/issues/1899
=> Fix #1899 double <br />

contact.php, install/resources/settings.xml
=> Fixes #1908 Add contact email setting

showthread.php
Fix #1210 soft deleted posts with showthread.php?pid=x#pidx
=> Fix #1210 soft deleted posts with showthread.php?pid=x#pidx

inc/functions.php, install/resources/mybb_theme.xml, reputation.php
Fixed wrong variable usage resulting in wrong reputation count.
https://github.com/mybb/mybb/issues/1897
Also added some missing `my_number_format()`s for reputation and cached
one forgotten template in reputation.php.
=> Fix #1897 wrong reputation count

forumdisplay.php, search.php
Fix #1869 Saving draft changes thread icon to replied in search page
=> Fix #1869 Saving draft changes thread icon to replied in search page

inc/class_parser.php
Fix #1836 split used in class_parser.php
=> Fix #1836 split used in class_parser.php

inc/datahandlers/pm.php, inc/datahandlers/post.php
Fix #1837 Setting safe_html to 1 for the parser though it isn't supported
=> Fix #1837 Setting safe_html to 1 for the parser though it isn't supported

admin/modules/forum/management.php, admin/modules/user/groups.php, admin/modules/user/users.php, inc/languages/english/admin/forum_management.lang.php, inc/languages/english/admin/global.lang.php, inc/languages/english/private.lang.php, install/resources/mybb_theme.xml
=> Fixes #1822 Username autocomplete for Group Leaders

inc/functions.php
Fix #1799 Weird IN_PORTAL checks
=> Fix #1799 Weird IN_PORTAL checks

inc/languages/english/showteam.lang.php, showteam.php
Fix #1907 Avay icon don't work properly at Forum team list
=> Fix #1907 Avay icon don't work properly at Forum team list

inc/languages/english/reputation.lang.php, reputation.php
Fix #1239 UX improvement for showing a user's reputations
=> Fix #1239 UX improvement for showing a user's reputations

member.php, modcp.php, usercp.php
Added several missing `isset()` checks.
https://github.com/mybb/mybb/issues/1928
=> Fix #1928 profile field warnings

inc/datahandlers/post.php
Fix #1463 Custom mod tools and inline moderation
=> Fix #1463 Custom mod tools and inline moderation

inc/functions_user.php, modcp.php, reputation.php
Fix #1931 Reputation page shows incorrect user title
=> Fix #1931 Reputation page shows incorrect user title

admin/modules/forum/management.php
=> Fixes #1905 Editing a forum allows to set a child forum as parent forum

global.php, inc/class_datacache.php, install/resources/settings.xml, stats.php
The 24 hours were added to the wrong site of comparison and resulted in
2 queries on every page load.
http://github.com/mybb/mybb/issues/1934
=> Fix #1934 wrong awaitngactivation time check

inc/adminfunctions_templates.php
As the title says. Makes it possible to modify global templates again.
https://github.com/mybb/mybb/issues/1903
=> Fix #1903 invalid find_replace_templatesets() $sid code

install/resources/upgrade12.php, install/resources/upgrade2.php, install/resources/upgrade3.php, install/resources/upgrade30.php, install/resources/upgrade5.php
=> Fixes #1926 Upgrades from <=1.2.14 fails

admin/modules/style/themes.php
=> Fixes #1941 Duplicating a theme doesn't duplicate the templates

inc/functions.php
#1939 @Destroy666x @euantorano
=> Fixes #1939 format_avatar caching issue

inc/languages/english/admin/config_thread_prefixes.lang.php
display -> displayed
link: http://community.mybb.com/thread-169341.html
https://github.com/mybb/mybb/issues/1951
=> Small typo in lang file - thread prefixes

readme.md
Would just like a bit of feedback in case someone has major objections to my rewording.
Changes:
- Add comma before "while..." because we're beginning an independent clause there
- `it makes a release` to `an official` release because MyBB.com per se doesn't make the release. The team does.
- Changed community link because it linked to MyBB.com which isn't directly to the community, and clarified the link destination respectively.
- Added link to docs site for support as well, and renamed the section to accommodate that there's now more than just a community link in that section.
=> [README] Reworded a few things, added Docs link

admin/modules/style/themes.php
=> Fixes #297 Problems on changing parent-theme

admin/modules/user/admin_permissions.php, admin/modules/user/groups.php, inc/datahandlers/pm.php, install/resources/adminoptions.xml, private.php
It's missing from the installation .xml file.
https://github.com/mybb/mybb/issues/1945
=> Fix #1945 wrong default spamlog admin permission

inc/db_base.php, inc/db_pdo.php, inc/db_sqlite.php
Fix #1871 fetch_array() issues
=> Fix #1871 fetch_array() issues

inc/languages/english/private.lang.php
=> correct error message for PM duplicates, fix #1979

install/resources/mybb_theme.xml
=> Fixes #1986 HTML bug in modcp template

inc/datahandlers/login.php, inc/datahandlers/user.php, inc/functions.php, inc/functions_archive.php, inc/functions_forumlist.php, inc/functions_search.php, inc/functions_user.php, misc.php
Same as #1991 but with the last change included. @euantorano @Destroy666x
=> Using strict equality checking for password comparisons for #1977

inc/db_mysql.php, inc/db_mysqli.php, inc/db_pgsql.php, inc/db_sqlite.php
Same as #1990 but with the changes I've suggested. @euantorano @Destroy666x
=> Fix #1933 is_numeric check in DB classes.

inc/datahandlers/post.php
=> require prefix setting not used on thread update, fix #1961

editpost.php
=> Fixes #2007 Preview table showing upon error

editpost.php
https://github.com/mybb/mybb/issues/2009
=> Fix #2009 poll options not saved in editpost.php

managegroup.php
Fix #1816 => Very inefficient managegroups.php code
=> Fix #1816 (Very inefficient managegroups.php code)

inc/functions.php, member.php
Fixes #1838
Deprecated the format_bdays function and use mktime for all birthdays.
=> Fixes #1838 Birthday bug

inc/functions_post.php
Fix #1911 Unnecessary code in functions_post.php
=> Fix #1911 Unnecessary code in functions_post.php

inc/functions_calendar.php
=> Fixes #1965 Calendar - problem with mini calendar

install/resources/upgrade3.php
Undefined `$settings` in one of RC (!) upgrade scripts.
https://github.com/mybb/mybb/issues/2048
=> Fix #2048 $settings undefined

admin/modules/home/credits.php
=> Fixes #2037 Fetching MyBB credits fails -> endless redirection

admin/modules/config/calendars.php, admin/modules/config/help_documents.php, admin/modules/config/mycode.php, admin/modules/config/post_icons.php, admin/modules/config/profile_fields.php, admin/modules/config/settings.php, admin/modules/config/smilies.php, admin/modules/config/thread_prefixes.php, admin/modules/user/banning.php, admin/modules/user/group_promotions.php
=> Fixes #2018 Use queried id instead of input

admin/inc/class_page.php, install/resources/mybb_theme.xml
=> Fixes #1963 Editing problem in IE11

private.php
Fix #1978 Send PM: Duplicate check not working for multiple recipients
=> Fix #1978 Send PM: Duplicate check not working for multiple recipients

inc/datahandlers/user.php
Fix #1820 Userhandler still doesn't delete some stuff
=> Fix #1820 Userhandler still doesn't delete some stuff

inc/functions.php, member.php
=> Fixes #1793 - Random generated password can throw error

inc/datahandlers/user.php, inc/functions.php
Fixes wrong timezone of users which are manually added via the Admin-CP by assigning the default board timezone.
https://github.com/mybb/mybb/issues/1999
=> Fix #1999 wrong timezone when adding user via Admin-CP

member.php
=> Fix 2091 - Escape Profile Field description and title on registration

install/resources/mybb_theme.xml, private.php
=> Fix #2093 - "Sending message to myself with BCC will cause an error"

inc/class_moderation.php, moderation.php
=> #2106 - Fix reports not getting deleted when soft deleting a post

inc/db_pdo.php
=> Fixes #2115 Inconsistent checks in db classes

global.php, inc/datahandlers/user.php, inc/functions.php, inc/languages/english/datahandler_user.lang.php, usercp.php, xmlhttp.php
Fix #1752 Bypassing Theme Permissions
=> Fix #1752 Bypassing Theme Permissions

inc/db_mysql.php, inc/db_mysqli.php
=> Fixes #2149 Show latin1 as latin 1 and not as cp1252

inc/class_captcha.php
https://github.com/mybb/mybb/issues/2126
=> Fixes reCAPTCHA issue (#2126) with HTTPS

newreply.php
=> Fixes #2122 Quick reply wrong $postcounter

newreply.php
=> Fixes #2163 Post subjects don't work correctly

install/resources/mybb_theme.xml
=> Fixes #2076 usercp_avatar HTML syntax error.

admin/modules/user/users.php
Fixes #2171  - escape_string_like()
=> Fixes #2171 - escape_string_like()

inc/class_parser.php
Corrected the regex so that it matches every whitespace character
except newlines.
https://github.com/mybb/mybb/issues/2143
=> Fix #2143 parser removes spacing between list elements

admin/modules/tools/mailerrors.php
#2105 
I haven't seen any reason why the quotes are added and haven't noticed any issues without them.
=> Fixes #2105 System Email Log Filters

admin/inc/class_form.php
=> Fixes #2164 output_row() $options['id']

global.php
Fixing the issue caused by not checking the user before updating. This should fix the immediate issue.
Signed-off-by: Euan Torano <euantorano@gmail.com>
=> Use `validate_user()` when updating theme

inc/functions_task.php, inc/languages/english/messages.lang.php
=> Fixes #2147 Task Manager does not work

inc/class_parser.php
=> Fixes #2132 video codes may not be loaded correctly

admin/index.php, inc/functions.php, inc/languages/english/admin/global.lang.php
Fixes #1992 
Couldn't find any reason why the messages language file wasn't being loaded.
=> Fixes #1992 send_pm bug in ACP

inc/languages/english/newthread.lang.php, newthread.php
=> Fixes #2088 New thread redirect is wrong.

inc/datahandlers/warnings.php, warnings.php
=> Fixes #2103 Undefined variable in warnings datahandlers

inc/functions.php
Simply casting will fix that error
#2209
=> Fixes #2209 Stats Cache Builder Bug

admin/inc/class_page.php, install/resources/mybb_theme.xml, install/resources/output.php, jscripts/general.js
=> Fixes #2199 - add keepelement to jquery-modal

install/resources/mybb_theme.xml
I earlier have tested it in Opera and now in FF - In Opera 63% was ok but in FF it doesnt work.
The max. witdh for this fix must be 60%
=> Fixes #2113

inc/functions_post.php, install/resources/mybb_theme.xml, member.php
Fixes #2090
Also fixes the find post/thread links in profiles.
=> Fixes #2090 $post['button_find'] doesn't check for permissions.

newreply.php
=> Fixes #2196 Subjects escaped twice in newreply.php

admin/modules/style/themes.php
=> Fixes #2220 Delete themestylesheet

inc/functions.php
=> Fixes #2235 Smilies "Show on clickable list?" doesn't work

inc/languages/english/misc.lang.php, install/resources/mybb_theme.xml
=> Fixes #2042 - Skype status icon broken

install/resources/mybb_theme.xml
#2081
@Destroy666x - I made a new PR, now it should be fine
=> Fixes #2081 - Wrong label & tooltip for "New Posts" icon

install/resources/mybb_theme.xml
* added missing ```</tr>```
* changed template version into 1807
=> Fixes #2262 Missing closing </tr> in template polls_editpoll

inc/class_error.php
=> Fixes #2234 MyBB logo on error page broken

install/resources/mybb_theme.xml, managegroup.php
=> Fixes #1817 managegroups.php pagination

misc.php
=> Fixes #1885 Who Posted not considering soft deleted posts.

inc/functions_warnings.php
Changes the doc block to at least describe a bit better how that function is used
#2212
=> Fixes #2212 Odd code in functions_warnings.php

inc/class_mailhandler.php, inc/mailhandlers/smtp.php
=> Fixes #2101 MailHandler accesses variables defined in SMTP

inc/datahandlers/user.php
=> Fixes #2085 UserDataHandler::clear_profile

inc/functions_post.php, reputation.php
=> Fixes #2074 Rating an unapproved post

inc/class_parser.php
=> Fixes #2068 HTML allowed - some weird replacements

install/resources/mybb_theme.xml
=> Fixes #2096 1.8 upgrade on page header javascript format error

admin/modules/user/admin_permissions.php
Fixes #1395 
Apparently Github doesn't link indenting large parts of code...
=> Fixes #1395 SQL error in Admin Permissions -> User Permissions

inc/languages/english/misc.lang.php
#1982 
This should fix this issue... for other missing lang strings it would be better to create a new issue (or update this PR)
=> Fixes #1982 - Missing $lang->error_invalidsearch

archive/index.php, forumdisplay.php, inc/languages/english/archive.lang.php, inc/languages/english/forumdisplay.lang.php, install/resources/mybb_theme.xml
=> Fixes #2214 Wrong error message

inc/functions_search.php
=> Fixes #1980 Nonexistent usernames cause invalid SQL on Search

install/resources/tasks.xml
=> Fixes #1974 Weird default user pruning task value

inc/functions_search.php
=> Fixes #2257 Default search doesn't find word with apostrophes

search.php
Fixes #1807
This should fix the mod permission issue.
=> Fixes #1807 search.php doesn't consider canviewdeleted mod permission

install/resources/upgrade26.php
=> Fixes #2278 PgSQL error when upgrading from <= 1.6.9

inc/functions.php
=> Fixes #1578 - PM subscriptions wrong username

inc/datahandlers/user.php
=> Fixes #1981 $this->delete_uids can be empty and throw SQL error

install/resources/mybb_theme.xml
- Added missing ```</td>```
- Changed version to 1807
=> Fixes #2283 Missing closing </td> in template report

admin/modules/forum/management.php, admin/modules/user/banning.php, admin/modules/user/groups.php, admin/modules/user/users.php, inc/languages/english/admin/user_banning.lang.php, inc/languages/english/global.lang.php, inc/languages/english/managegroup.lang.php, inc/languages/english/member.lang.php, inc/languages/english/memberlist.lang.php, inc/languages/english/modcp.lang.php, inc/languages/english/private.lang.php, inc/languages/english/search.lang.php, inc/languages/english/usercp.lang.php, install/resources/mybb_theme.xml, xmlhttp.php
Fixes #1567
- Shortens minimumInputLength to ~~1~~ 2
- Removed maximumSelectionSize on all select2 that aren't multiples
- Tied maximumSelectionSize to maxpmrecipients for PMs
- Centralized select2 placeholder language strings to the global language file (pointless to keep the same string scattered across 7 language files)
=> Fixes #1567 It's impossible to send a PM to a user with a short username

admin/modules/user/users.php
=> Fixes #2064 Inducing PHP Warning in User management

install/resources/mybb_theme.xml, jscripts/inline_moderation.js
Fixes #2071 - Inline moderation on classic mode
=> Fixes #2071 - Inline moderation on classic mode

admin/inc/class_page.php
Fixes #2231 - Deprecate get_alt_bg()
=> Fixes #2231 - Deprecate get_alt_bg()

warnings.php
Fixes #2036 - warnings.php wrong $lang
=> Fixes #2036 - warnings.php wrong $lang

inc/class_custommoderation.php
=> Fixes #2310 SQL error when posting new post with custom moderation tool

private.php
Fixes #2313 - Not a good way to update counters
=> Fixes #2313 - Not a good way to update counters

readme.md
You cannot contribute to a series that is officially no longer supported. Perhaps 2.0 should also have info regarding its branch alongside 1.6 and 1.8.
=> Contributions to MyBB 1.6 has ended.

inc/functions.php
=> Fix #2319 Enable CURLOPT_FOLLOWLOCATION for fetch_remote_file() 

admin/modules/style/themes.php, global.php
As the title says, more details in the post linked in the issue - it was
possible to save it as a non-array in earlier MyBB versions.
Also added the error to one more place so that the admin will be
notified of the issue.
https://github.com/mybb/mybb/issues/2301
=> Fix #2301 $theme['disporder'] may be not an array

xmlhttp.php
=> Fixes #2203 Click and Hold erases thread prefix in 1.8.6

inc/tasks/dailycleanup.php
=> Fixes #2314 Wrong PM update array code

calendar.php
A weird comparison was used, the `$hascustomtitle` variable also wasn't
used efficiently..
https://github.com/mybb/mybb/issues/2327
=> Fix #2327 wrong usertitles in calendar

install/index.php
As the title says, thus admins my end up with wrong setting if they trust it. Also added a check whether the generated Email is indeed an Email (it may be anything)..
https://github.com/mybb/mybb/issues/2330
=> Fix #2330 port not stripped from the generated cookie domain

inc/functions_post.php, newreply.php, polls.php, printthread.php, ratethread.php, search.php, usercp2.php
Also added several other `!isset()` checks just in case a plugin or
whatever will miss definition of these globals.. And shortened some
conditionals to simple assignments.
https://github.com/mybb/mybb/issues/2224
=> Fix #2224 no inline moderation checkbox in quick reply post

install/resources/mybb_theme.xml, jscripts/select2/select2.css
Fixes #2069 - Search container width
=> Fixes #2069 - Search container width

inc/datahandlers/post.php
=> Fixes #2072 Last Post Issue

install/resources/mybb_theme.xml
Fixes #2340 - usercp_editlists_user - wrong lang string in title
=> Fixes #2340 - usercp_editlists_user

inc/class_parser.php
Cartridge returns, for they are the workings of the devil!
=> Fixed an amusing typo in a comment in class_parser.php

admin/inc/class_form.php
=> Fixes #1832 Numeric fields - default values lower than minimum

search.php
https://github.com/mybb/mybb/issues/2350#issuecomment-190410082
My pull request for #1807 accidentally broke the post search for everyone. This will fix it.
=> Fixes post search issue introduced in #1807

inc/functions_upload.php
=> Fixes #2357 - BMP images for avatars

usercp.php
=> Fixes #2348 Useless subscription guest checks in UCP

global.php, install/resources/mybb_theme.xml
=> Fixes #2236 Buddy popup problem when user doesn't have any permissions

install/resources/mybb_theme.xml
=> fix #2377: referral disabled -> memberlist: wrong colspan

captcha.php
=> Fix #2394 - Use rand() instead of my_rand() to improve captcha performance

htaccess.txt
=> Fixes #2211 - .htaccess

editpost.php, inc/functions_modcp.php, modcp.php, moderation.php
=> Fixes #2251 Bad words not parsed in breadcrumbs etc.

usercp.php
Fixes #2057 - PM folder language problem
=> Fixes #2057 - PM folder language problem

admin/modules/user/banning.php, inc/languages/english/admin/config_banning.lang.php, inc/languages/english/admin/user_banning.lang.php
=> Fixes #2385 - missing lang string

admin/jscripts/themes.js, admin/modules/user/banning.php
Fixes #1056 - ACP: Replace hardcoded placeholder language string with an actual language variable
WIP!
=> Fixes #1056 - Replace hardcoded lang strings

install/resources/language.lang.php, install/upgrade.php
As the title says. It needs an argument.
https://github.com/mybb/mybb/issues/2417
=> Fix #2417 upgrade print_error() warning

admin/modules/user/users.php, install/resources/mybb_theme.xml, jscripts/bbcodes_sceditor.js, jscripts/sceditor/textarea_styles/jquery.sceditor.buttons.css, jscripts/sceditor/textarea_styles/jquery.sceditor.default.css, jscripts/sceditor/textarea_styles/jquery.sceditor.modern.css, jscripts/sceditor/textarea_styles/jquery.sceditor.monocons.css, jscripts/sceditor/textarea_styles/jquery.sceditor.mybb.css, jscripts/sceditor/textarea_styles/jquery.sceditor.office-toolbar.css, jscripts/sceditor/textarea_styles/jquery.sceditor.office.css, jscripts/sceditor/textarea_styles/jquery.sceditor.square.css
=> Fix #2228 SCEditor - Duplicate tags after re-election.

admin/modules/tools/warninglog.php, admin/modules/user/banning.php, admin/modules/user/groups.php, admin/modules/user/users.php, announcements.php, editpost.php, forumdisplay.php, global.php, inc/functions_forumlist.php, inc/functions_post.php, member.php, modcp.php, moderation.php, newreply.php, newthread.php, polls.php, portal.php, private.php, search.php, showthread.php, usercp.php, xmlhttp.php
Fixes #1631
Fixed remaining issues and locations that were missed originally.
=> Fixes #1631 username's should be htmlspecialchars_uni()'d

admin/modules/user/users.php, inc/functions.php, install/resources/settings.xml
I didn't include `$change_dir` because it doesn't seem to be implemented
correctly anyways (I'll create an issue later).
https://github.com/mybb/mybb/issues/2363
Hope it gets merged before other conflicts arise.
=> Fix #2363 per theme default avatar

install/index.php
=> Fixes #2422 Installation fails on aggressive opcache settings

contact.php
=> Fixes #2107 contact form not stripping html code in emails

editpost.php
=> Fixes #2434 missing_username error when editing a deleted user's post

inc/class_moderation.php
=> Fixes #2436 Attachment counter wrong after merging posts

inc/datahandlers/post.php
=> Fixes #2022 Close Thread doesn't work via reply

member.php
=> Fixes #1988 Redirect problem with IDN after login

install/resources/mybb_theme.xml, jscripts/post.js
=> Fixes #1647 Remove Attachment not working without refresh

admin/modules/tools/system_health.php
Addition to https://github.com/mybb/mybb/pull/2421
=> Correct CHMOD link

install/resources/language.lang.php
http://docs.mybb.com/CHMOD_Files.html is dead
=> Send users who click "chmod" somewhere helpful

inc/functions_serverstats.php
=> Fix #2443 MyBB not respecting https:// URLs of certain resources

moderation.php
=> Fixes #2447 SQL error on post split with ONLY_FULL_GROUP_BY enabled

inc/languages/english/admin/tools_system_health.lang.php, install/resources/language.lang.php
=> Fixes #1729  updates 2 broken URLs

inc/functions.php, inc/languages/english/misc.lang.php, install/resources/mybb_theme.xml, misc.php
=> Fixes #2256 No smilies/post icons

member.php
=> Fixes #2456 Hash instead of the password at the "forgot my password"

admin/modules/user/users.php
=> Fixes #2431 Default avatar broken on ACP when using a full URL

install/resources/mybb_theme.xml
=> Fixes #2446 Mark All Reports bug

admin/modules/config/module_meta.php, admin/modules/config/report_reasons.php, inc/class_datacache.php, inc/functions_modcp.php, inc/languages/english/admin/config_module_meta.lang.php, inc/languages/english/admin/config_report_reasons.lang.php, inc/languages/english/admin/tools_adminlog.lang.php, inc/languages/english/report.lang.php, install/index.php, install/resources/adminoptions.xml, install/resources/mybb_theme.xml, install/resources/mysql_db_inserts.php, install/resources/mysql_db_tables.php, install/resources/pgsql_db_tables.php, install/resources/sqlite_db_tables.php, install/resources/upgrade36.php, install/upgrade.php, modcp.php, report.php
Fixes #1223 Report reasons enhancements
I haven't tested using PostgreSQL or SQLite so please make sure you do that before merging! :smile:
=> Fixes #1223 Report reasons enhancements

admin/index.php
=> Fixes #2427 Admin interface issues on IPv6

inc/functions_indicators.php
Fixes #2167
$fid can be a CSV list with multiple forums so ```forum_permissions($fid);``` was apparently wrong. This is unrelated to the bug but fixing wasn't too difficult.
=> Fixes #2167 Unread indication doesn't work for guests

inc/languages/english/moderation.lang.php
i'm not a feminist or anything, but this always annoys me whenever i ban someone.
=> gender neutral pronoun

install/upgrade.php
=> Fix #2473 Use main datacache instance during upgrade

install/resources/mybb_theme.xml
in modcp_announcements_day and moderation_delayedmoderation_date_day
#2474
=> Fixes #2474 - Redundant apostrophe

admin/modules/config/report_reasons.php
Fixes #2477 
Also fixes issue with output_confirm_action using a qid instead of rid
=> Fixes #2477 Invalid table name in Report Reasons

admin/modules/style/themes.php
=> Fixes #2426 Cannot delete theme on postgres

install/resources/mybb_theme.xml
=> Fixes #2485 Expand/collapse theads not fully implimented

install/resources/mybb_theme.xml
redundant closing form tag
#2469
=> Fixes #2469 - modcp_announcements_delete

global.php
#1789 Simply fixed the statement as I don't think that discussing the function of a super admin at this point of 1.8 is really necessary.
=> Fixes #1789 Weird global.php is_super_admin() check

modcp.php
=> Fixes #2502 by removing the addition

admin/modules/tools/backupdb.php
=> Fixes #2125 Unable To Perform a Database Backup

usercp.php
=> Fixes #2509 by adding the old if statement from 1.8.7

admin/modules/style/templates.php, inc/languages/english/admin/style_templates.lang.php
=> Fixes #2078 by disallowing underscores in prefixes

inc/tasks/checktables.php
=> Fixes #2061 check tables incorrect if check

install/resources/mybb_theme.xml
=> Fixes #2135

LICENSE
Fixes #2514 - Add a licence file LGPL v3
Make GitHub and others happier!
=> Fixes #2514 - Add a licence file LGPL v3

admin/modules/style/themes.php
=> Fix renaming a stylesheet doesn't recache it

inc/languages/english/admin/config_attachment_types.lang.php
Fixes #2530 - Outdated MIME types - URL link
=> Fixes #2530 - Outdated MIME types - URL link

admin/modules/style/templates.php
=> Fix #674 Line breaks in templates search fails

admin/modules/home/index.php, admin/modules/tools/adminlog.php, admin/modules/user/awaiting_activation.php, admin/modules/user/module_meta.php, inc/languages/english/admin/tools_adminlog.lang.php, inc/languages/english/admin/user_awaiting_activation.lang.php, inc/languages/english/admin/user_module_meta.lang.php, inc/languages/english/global.lang.php
Fixes #1569 
Went with a dedicated page for users awaiting activation based on my plugin [Activate Users From Mod CP](https://github.com/PaulBender/Activate-Users-From-Mod-CP)
=> Fixes #1569 "Email Verification & Administrator Activation" usless

inc/languages/english/usercp.lang.php
Fixes #2556
Made the link https://gravatar.com/
It redirects to users regional language accordingly. I have edited my bug report thread with updated links too: [Gravatar link updation](https://community.mybb.com/thread-206458.html)
=> Fixes #2556 Gravatar link updation

inc/functions.php, install/resources/mybb_theme.xml, install/resources/settings.xml, jscripts/general.js
=> Fix #2464 Add option to set cookies with Secure flag

calendar.php
=> Fix #511 Calendar, Week Overview: Week period calculated wrong

inc/functions_modcp.php, inc/languages/english/messages.lang.php, install/resources/settings.xml
=> Fixes #2488

install/resources/mybb_theme.xml
added {$collapsedthead['quickreply']} to private_quickreply and showthread_quickreply
=> add {$collapsedthead['quickreply']}

inc/class_moderation.php
=> Fixes #2419 "Notice: Undefined index: num_threads" when moving threads

newreply.php
=> Fix#2560 Empty index operator error on php 7.1

inc/languages/english/admin/user_admin_permissions.lang.php
=> Fixes #2130 can not set permissions on another super admin

install/resources/settings.xml
Fixes #2558 - Disable edit by timestamp for admins also disables for moderators
=> Fixes #2558 - Disable edit by timestamp... - change description

admin/index.php, inc/languages/english/admin/global.lang.php
=> Fix#2551 Delete invalid PIN error message on admin login

install/resources/mybb_theme.xml
=> Fix#2564 Correctly mark collapsed thead in thread notes

inc/class_moderation.php
=> Fixes #1751 Splitting thread decrease the thread count of user

inc/class_parser.php
=> Fix #2547 XSS in URL BBCode

admin/modules/forum/management.php, inc/class_custommoderation.php, inc/class_moderation.php, inc/languages/english/admin/forum_management.lang.php
#1609 (old PR: #1920)
Fixed the smaller issues mentioned in the previous PR. Only pagination is still missing. @Destroy666x
=> Fix #1609 forum deletion

inc/class_parser.php
=> Fix #2572 Word filter iterates over replacement strings

inc/functions.php
=> Fixes #2580 File Verification and .txt files

install/resources/mybb_theme.xml
=> Fixes #2588 Missing line break in New Thread post options

member.php
=> Fix #2591 Show/Hide custom profile fileld on member profile

forumdisplay.php
=> Fixes #2592 Approve/unapprove threads moderator permission broken

install/resources/mybb_theme.xml
Fixes #2599 - delete extra space
=> Fixes #2599 - delete extra space

newreply.php
=> Fixes #2585 - Quoting posts removes moderator options under certain conditions

inc/functions.php, misc.php
=> Fix #2428 Remove <script> and <style> tags with content on help docs.

install/resources/mybb_theme.xml, memberlist.php
=> Fixes #2575 Contact Details

install/resources/mybb_theme.xml, jscripts/general.js
...where in the Who Posted modal dialog, sorting links redirected to a
new blank page. #2590
=> Fixes #2590

inc/datahandlers/post.php, install/resources/mybb_theme.xml, newreply.php, newthread.php
=> Fixes #2491 New reply mod options do not check specific moderator per…  

inc/datahandlers/pm.php, inc/functions_post.php, member.php
Fix #2594 
Fix #1834
[PM's links in header are](https://github.com/mybb/mybb/issues/2594#issuecomment-271076005) already fixed in 1.8.9.
=> Fix #2594 and #1834 PM's to users with disabled PM's

modcp.php
...where input fields were unnecessarily encoded.
#2541
=> Fixes #2541

admin/modules/user/mass_mail.php, admin/modules/user/users.php, calendar.php, global.php, inc/datahandlers/user.php, inc/functions.php, inc/functions_calendar.php, member.php, modcp.php
=> Fix #2517 Invalid values used with operators expecting numbers raise E_WARNING on PHP 7.1

inc/class_moderation.php, inc/datahandlers/post.php
=> Fix #2516 - Last post not updated when approving the first post using inline mod tools

inc/languages/english/global.lang.php, inc/languages/english/index.lang.php, install/resources/mybb_theme.xml
First commit for #1583
@MyBB devs - it would be nice to have more improvements from the list
added in 1.8.9 release. At least for the front-end part. Many of the proposed changes are really nice and useful.
@Destroy666x @Stefan-ST @JN-Jones @JordanMussi @Ben-Conway @PaulBender  and others
=> Add "Mark site as read" into footer (#1583)

admin/inc/class_page.php, install/resources/mybb_theme.xml, install/resources/upgrade38.php
=> #2464-related version bumps & 1.8.9 upgrade file

forumdisplay.php, global.php, index.php, install/resources/mybb_theme.xml
Fixes issues with #2544
https://github.com/mybb/mybb/commit/3ed92adcc1338a31330a2ba294aa2385d0c60083#commitcomment-20406009
=> Fixes #2544 Add "Mark site as read" into footer

inc/datahandlers/post.php
=> Fixes #2612 last post info is not updating properly

admin/modules/user/group_promotions.php
Fixes #2629 
Created a separate check for the time fields.
=> Fixes #2629 Group promotions bug

member.php, modcp.php, usercp.php
=> Fix #2645 - PHP 7.1 Illegal string offset warning

admin/modules/config/settings.php
#2643 - cleaner code
Thx @Shade- and @doylecc
=> Fixes #2642 - Stats page refreshing issue

inc/datahandlers/login.php, inc/datahandlers/user.php, inc/functions_user.php
=> Fix #2649 Rewrite create_password_hash() usage to accept array of password parameters

usercp.php
=> Fix #2677 Add new hook in User CP's Change Avatar section

admin/index.php
=> Fix #2675 Add Referrer-Policy header on ACP pages

moderation.php
=> Fix #2662 - Add hook for posts multimove in moderation tools

admin/index.php
Part of #2666 
Adds the Admin CP login hooks [I wanted](https://community.mybb.com/thread-208322-post-1264030.html#pid1264030)
=> Part of #2666 Missing Plugin Hooks in ACP Users Modul

inc/3rdparty/2fa/GoogleAuthenticator.php
See #2635.
Updates the library with no formatting changes (as the previous version didn't adhere to coding style either).
=> Fix #2635 - Update PHPGangsta/GoogleAuthenticator

install/index.php, install/resources/language.lang.php, install/resources/output.php, install/upgrade.php
-Added translation string for 'Upgrade Complete'
-Set 'Welcome' translation string as default value on output header
=> Fixed installer/upgrade translations

inc/functions_modcp.php, modcp.php
=> Fixes #2685 - Mod CP hooks

admin/modules/tools/adminlog.php, admin/modules/tools/mailerrors.php, admin/modules/tools/maillogs.php, inc/languages/english/admin/tools_adminlog.lang.php
=> Fixes #2683 Issues with Admin Logging and email pruning

member.php
=> Fix #2681 - orphaned variable

inc/datahandlers/user.php
=> Fixes #2575

inc/functions_online.php
=> Fix for #2610

admin/modules/config/mycode.php, inc/languages/english/admin/config_mycode.lang.php
=> Fixes #2638

inc/functions_post.php
#2634
I switched the two snippets just to prioritize deleted over ignored post; it seemed more logical to me.
=> Fixes #2634

admin/modules/user/awaiting_activation.php, inc/languages/english/admin/user_awaiting_activation.lang.php
Fixes #2652 - Notification email not sent after ativation
All credits go to @MattRogowski
=> Fixes #2652 - Notification email not sent after ativation

admin/modules/style/themes.php
=> Fixes #2483

inc/languages/english/misc.lang.php
=> Fixes #2703

usercp.php
=> Fix #2705 mybbuser cookie is set without httponly when changing password

inc/functions_online.php
=> Fixes #2694

inc/functions.php
=> Fix fetch_remote_file() related problems

inc/functions.php, inc/languages/english/admin/global.lang.php, inc/languages/english/global.lang.php
Fixes #2724 
Relative dates will show the full date and time.
Yesterday/Today will show full date.
=> Fixes #2724 Hover on Relative time to Show Exact date/time

admin/modules/user/users.php
=> Fixes #2727 Merge hook not working correctly

install/resources/mybb_theme.xml
=> Fixes #2736 - Missing closing <strong> tags

install/resources/mybb_theme.xml
=> Fixes #2738 - Redundant <tr> tag

inc/languages/english/misc.lang.php, install/resources/mybb_theme.xml, misc.php
=> Fixes #2733 Issues with the IM center pop-up

inc/functions.php
=> Fix #2693 Incorrect post-login redirect URL on private networks and localhost

inc/db_pgsql.php
=> Fix #2731 Add listing UNIQUE keys in DB_PgSQL::show_create_table()

misc.php
=> Fix XSS issue in PR #2714

install/resources/mysql_db_inserts.php, install/resources/upgrade40.php, install/resources/upgrade41.php
This PR resolves https://github.com/mybb/mybb/issues/2740
=> PR for issue #2740

install/resources/mybb_theme.xml
=> Fixes #2769

install/resources/mybb_theme.xml
=> Fixes #2759 Go To in private.php doesn't work

install/resources/mybb_theme.xml, misc.php
=> Fixes #2603 ForumDisplay: Who Posted Inoperable Without JavaScript

admin/modules/forum/attachments.php
=> Fixes #2723 Select all doesn't work in ACP Attachments

member.php
=> Fixes #2763 Random password at registration doesn't work

install/resources/mybb_theme.xml
=> Fixes #2756 $post['poststatus'] missing from postbit

install/resources/mybb_theme.xml
Fixes comment here: https://github.com/mybb/mybb/pull/2757#issuecomment-312932548
=> More flexible styling for postbit_status

archive/print.css, archive/screen.css, install/resources/mybb_theme.xml
#2792  - Maximum width of images in printthread.php and archive mode
=> Fixes #2792

inc/languages/english/member.lang.php, inc/languages/english/usercp.lang.php
https://community.mybb.com/thread-212151.html
Thx to @Ashley1
=> Replace <acronym> with <abbr> - follow HTML5 standards

admin/inc/class_page.php, admin/styles/default/main.css
=> Fixes #2820 - CSS comments marker

member.php
=> Fixes #2811

admin/modules/tools/statistics.php
=> Fixes #2539 Overall Statistics Problem

admin/index.php
Fixes #2700 
Now the default/global admin theme and language is used for login and the user's preference is only used once they are fully authenticated.
=> Fixes #2700 Custom Admin Theme Set Before Completed Login with 2FA

inc/functions.php
Not using isset() will return true if the user_cache exists even though the given uid might not be set.
This can result in an undefined offset error.
=> use isset to check if it's set and not null

admin/inc/class_page.php, admin/modules/forum/attachments.php, admin/modules/user/groups.php, install/resources/mybb_theme.xml, install/resources/output.php, jscripts/general.js
Fixes #2110 
Also changes #2773 PR for issue #2723 to use allbox
---
**This PR:**
- changes 1 template
- changes 1 `.js` file
=> Fixes #2110 Still not all checkall checkboxes were changed to the new allbox

member.php
=> Fixes #2765 $errors array needs explicit declaration in member.php

admin/modules/user/groups.php, inc/languages/english/admin/user_groups.lang.php
Fixes #2691 Can create multiple usergroups with the same name
---
**This PR:**
- changes 1 language file
=> Fixes #2691 Can create multiple usergroups with the same name

admin/inc/functions_themes.php, admin/modules/config/languages.php, inc/3rdparty/diff/Diff.php, inc/3rdparty/diff/Diff/Engine/Native.php, inc/3rdparty/diff/Diff/Engine/Shell.php, inc/3rdparty/diff/Diff/Engine/String.php, inc/3rdparty/diff/Diff/Engine/Xdiff.php, inc/3rdparty/diff/Diff/Exception.php, inc/3rdparty/diff/Diff/Mapped.php, inc/3rdparty/diff/Diff/Op/Add.php, inc/3rdparty/diff/Diff/Op/Base.php, inc/3rdparty/diff/Diff/Op/Change.php, inc/3rdparty/diff/Diff/Op/Copy.php, inc/3rdparty/diff/Diff/Op/Delete.php, inc/3rdparty/diff/Diff/Renderer.php, inc/3rdparty/diff/Diff/Renderer/Context.php, inc/3rdparty/diff/Diff/Renderer/Inline.php, inc/3rdparty/diff/Diff/Renderer/Unified.php, inc/3rdparty/diff/Diff/Renderer/Unified/Colored.php, inc/3rdparty/diff/Diff/ThreeWay.php, inc/3rdparty/diff/Diff/ThreeWay/BlockBuilder.php, inc/3rdparty/diff/Diff/ThreeWay/Op/Base.php, inc/3rdparty/diff/Diff/ThreeWay/Op/Copy.php, inc/functions.php
=> Fixes #2743 Replace features deprecated in PHP 7.2

install/resources/mybb_theme.xml, search.php
=> Fixes #2829

modcp.php
=> Fixes #2073

admin/inc/functions_themes.php, inc/class_datacache.php
=> Fix #2824 Counting of non-countable objects emits Warning on PHP 7.2

inc/class_parser.php
=> Fixed #2821

moderation.php
=> Fixes #2813

inc/class_parser.php
=> Fix #2741 Missing plugin hooks in postParser

inc/functions_indicators.php
=> Fixes #2836 Mark All Forums Read error

inc/functions.php, moderation.php
=> Fixes #2392

inc/functions_search.php
Fixes #2845
* Queries replaced by existing `get_child_list()`
* Check that `$search['forums']` is actually set
* Unused variables `$searchin` and `$user_groups` removed
* Permission checks removed (`get_unsearchable_forums()` already excludes these forums)
* DBMS check removed from fulltext search (which only works with MySQL)
=> Fixes #2845 Incorrect queries in functions_search.php (SQLite and PgSQL)

inc/datahandlers/user.php, inc/languages/english/datahandler_user.lang.php, install/resources/mybb_theme.xml, member.php, xmlhttp.php
Fixes #1653 
---
**This PR:**
- changes 1 template
- changes 1 language file
=> Fixes #1653 xmlhttp improvements

inc/class_session.php
=> Fixes #2853 Show Forum Internal Error

install/resources/mybb_theme.xml
trow1 should be trow2 - member_resetpassword
=> trow1 should be trow2 - member_resetpassword

inc/datahandlers/pm.php
=> Fix #2869 Add post-insert hooks to PMDataHandler

inc/mailhandlers/smtp.php
Fixes #2798
This PR doesn't add DIGEST-MD5.
=> Fixes #2798 SMTP authentication problem with DIGEST-MD5 or CRAM-MD5

global.php
#2851
@JordanMussi asked me to extend my PR allowing access to the contact page when the board is closed, but since I'd deleted the original forked repository I couldn't figure out the git magic to extend the original PR, so I've created this new one. #2851 can be closed.
=> extension of PR #2851

forumdisplay.php, search.php, showthread.php
=> Fixes #2767 Registered group bugs out when they have 'can view deletion notices' and cant see new posts.

admin/modules/config/banning.php, admin/modules/user/banning.php
=> Fixes #2803 Admin Panel (config-banning) has ban adding below the ban list

inc/datahandlers/user.php
Fixes #2875 
All credits go to @Shade, thank you!
=> Fixes #2875

inc/languages/english/member.lang.php, member.php
Fixes #2790 
---
**This PR:**
- changes 1 language file
=> Fixes #2790 Language string not available outside datahandler

member.php
Fixes #2879 Password security validation incorrect from #2790
=> Fixes #2879 Password security validation incorrect from #2790

inc/functions.php, modcp.php, usercp.php, warnings.php
=> Fixes #1783 Warnings, suspention times, etc. Should use the nice_time function

member.php
=> Revert "Fixes #2879 Password security validation incorrect from #2790"

inc/class_stopforumspamchecker.php, inc/languages/english/global.lang.php
Fixes #2172 
This is a replacement for #2858 and follows the comments from @dvz.
=> Fix #2172 - Stopforumspam Reserved and Private IP ranges

inc/3rdparty/diff/Diff/Engine/Native.php
fix #2797
https://github.com/mybb/mybb/issues/2743#issuecomment-341786421
based on patches shared on https://core.trac.wordpress.org/ticket/41526
=> Update Horde_Text_Diff_Engine_Native, fix array pointer issues

install/resources/upgrade41.php
=> Fixes #2901 Remove Duplicate WHERE in update query

admin/modules/config/languages.php
=> Fixes #2922 - rel="noopener" in language pack

admin/inc/functions_themes.php
=> Fix functions_themes.php for PHP 7.2 (fixes #2927)

inc/class_mailhandler.php
Due to my general GitHub noobishness, I ended up fixing 3 issues in one PR so this is a carbon copy without the other fixes.
=> Update to class_mailhandler.php (fixes #2883)

admin/modules/tools/modlog.php
Second part of this issue #2685 - we forgot to ACP mod logs
Credits @Supryk
=> #2685 - missing plugin hook - ACP mod logs

ratethread.php
This PR removes unnecessary code as pointed out in #2903.
=> Removed unnecessary code from ratethread.php

calendar.php
Fixes #2854 
This imports my fix from #2543 to the dayview and weekview actions, basically preventing the calendar from going back before 1901.
=> Fixes #2854 MyBB Calendar PHP Error

memberlist.php
=> Fixes #309 Memberlist searching case sensitive with PostrgreSQL

usercp.php, warnings.php
Fixes #2881 Unknown error occurred returned for several error() calls in warnings.php
See https://github.com/mybb/mybb/issues/2881#issuecomment-346672798 for change details.
=> Fixes #2881 Unknown error occurred returned for several error() calls in warnings.php

inc/functions_post.php, install/resources/mybb_theme.xml, jscripts/general.js, moderation.php
=> Fixes #2925 Convert IP address pages to modal popup

inc/class_core.php, install/resources/mybb_theme.xml, install/resources/mysql_db_tables.php, install/resources/pgsql_db_tables.php, install/resources/sqlite_db_tables.php, install/resources/upgrade42.php, polls.php, showthread.php
=> Fixes #2948 Guest poll voting updates

inc/views/base/forumbit/depth_2/last_post.twig, inc/views/base/forumbit/depth_2/last_post_hidden.twig, inc/views/base/forumbit/depth_2/last_post_never.twig, inc/views/base/usercp/subscribed_forum_row.twig, inc/views/base/usercp/subscribed_forums.twig, usercp.php
Part of #2972. Translates the forum subscriptions in the user CP to Twig.
=> Translating forum subscriptions to Twig

inc/functions.php
=> Fix #2977 Add plugin hook to format_name()

inc/languages/english/moderation.lang.php, moderation.php
Fixes #3015
Delayed moderation move thread was checking current forum settings and permissions, not the new forum. Also added missing checks for move to non mod forum mod permission and move to same forum.
=> Fixes #3015 Delayed Moderation

inc/views/base/polls/editpoll.twig, inc/views/base/polls/newpoll.twig, inc/views/base/polls/showresults.twig, polls.php
Working on #2972 
This PR is for the polling pages (polls.php)
=> Working on #2972 Template Conversion to Twig Format (polls.php)

contact.php, inc/views/base/contact/contact.twig
Working on #2972 
This PR is for the contact form (contact.php).
=> Working on #2972 Template Conversion to Twig Format (contact.php)

inc/functions.php
#2916
Sample `sha512` checksum set for MyBB 1.8.14: https://gist.githubusercontent.com/dvz/37118aabc70d2e3787d649123da947bd/raw/b77a994d03f65d792d73fe744f893e7a9deaef55/release_mybb_1814.txt (URL hardcoded in https://github.com/mybb/mybb/blob/mybb_1814/admin/modules/tools/file_verification.php#L39)
=> Fix #2916 Upgrade File Verification hash algorithm

inc/views/base/moderation/confirmation.twig, inc/views/base/moderation/delayedmoderation.twig, inc/views/base/moderation/deletepoll.twig, inc/views/base/moderation/deletethread.twig, inc/views/base/moderation/inline_deleteposts.twig, inc/views/base/moderation/inline_deletethreads.twig, inc/views/base/moderation/inline_mergeposts.twig, inc/views/base/moderation/inline_moveposts.twig, inc/views/base/moderation/inline_movethreads.twig, inc/views/base/moderation/inline_splitposts.twig, inc/views/base/moderation/merge.twig, inc/views/base/moderation/move.twig, inc/views/base/moderation/purgespammer.twig, inc/views/base/moderation/split.twig, inc/views/base/moderation/threadnotes.twig, inc/views/base/moderation/viewthreadnotes.twig, moderation.php
=> Working on #2972 Template Conversion to Twig Format (moderation.php)

inc/views/base/member/activate.twig, inc/views/base/member/coppa_form.twig, inc/views/base/member/emailuser.twig, inc/views/base/member/login.twig, inc/views/base/member/lostpw.twig, inc/views/base/member/resendactivation.twig, inc/views/base/member/resetpassword.twig, inc/views/base/member/viewnotes.twig, member.php
#2972 for member.php
This includes all member.php pages except for the registration and profile pages (due to how complex they are; I'll do those as separate PRs).
=> Working on #2972 Template Conversion to Twig Format (member.php)

inc/functions_online.php, inc/views/base/online/online.twig, inc/views/base/online/today.twig, online.php
For #2972 
```diff
+ online -> online/online.twig
- online_refresh
- online_row
- online_row_ip
- online_row_ip_lookup
+ online_today -> online/today.twig
- online_today_row
```
=> #2972 (online.php) online user list to twig

calendar.php, inc/views/base/calendar/dayview.twig, inc/views/base/contact/contact.twig, inc/views/base/managegroup/joinrequests.twig, inc/views/base/managegroup/managegroup.twig, inc/views/base/moderation/viewthreadnotes.twig, inc/views/base/polls/editpoll.twig, inc/views/base/polls/newpoll.twig, inc/views/base/postbit/postbit.twig, inc/views/base/sendthread/sendthread.twig, inc/views/base/warnings/view.twig, inc/views/base/warnings/warn.twig, inc/views/base/warnings/warnings.twig, managegroup.php, memberlist.php, moderation.php, warnings.php
This PR updates some of my already merged requests for #2972 with some minor improvements.
- Using loop.last for comma separated lists (calendar birthdays).
- Using trans in place of sprintf.
- Corrected title on warning (was using setting bburl instead of bbname).
- Added `<label>` to places where it was missing.
- Using the twig nl2br where needed instead of php nl2br.
=> Updates for #2972

editpost.php, inc/views/base/editpost/editpost.twig
#2972 for editing a post (editpost.php)
Also changed the attachment error bit to use inline_error (to make it consistent with newreply.php and newthread.php).
=> Working on #2972 Template Conversion to Twig Format (editpost.php)

inc/views/base/newreply/newreply.twig, newreply.php
#2972 for posting a new reply (newreply.php)
=> Working on #2972 Template Conversion to Twig Format (newreply.php)

inc/functions.php, inc/views/base/newthread/newthread.twig, newthread.php
#2972 for posting a new thread (newthread.php)
=> Working on #2972 Template Conversion to Twig Format (newthread.php)

inc/views/base/member/profile.twig, member.php
#2972 for member profiles (member.php?action=profile)
Also fixes #2698
=> Working on #2972 Template Conversion to Twig Format (member profile)

inc/views/base/usercp/changename.twig, inc/views/base/usercp/email.twig, inc/views/base/usercp/password.twig, usercp.php
Part of #2972.
This converts the following user CP pages to Twig:
- Change password
- Change email address
- Change username
=> Updating user CP email, password and username pages to use Twig

inc/views/base/usercp/editsig.twig, inc/views/base/usercp/editsig_suspended.twig, usercp.php
Part of #2972.
This converts the user CP signature page to Twig.
=> Updating user CP signature page to use Twig

online.php
Fixes #3040 - Online Today Pagination
=> Fixes #3040 - Online Today Pagination

inc/class_parser.php
This PR fixes an issue with the auto URL parser executing before image parser, causing [img] BBCode to be ineffective.
=> Prioritized img parsing before auto_url to fix breaking changes in #2968

inc/class_datacache.php
=> Fixes #3061 SQL error with board stats on Postgres

inc/functions.php, inc/views/base/partials/multipage.twig
#2972 for the multipage function.
Resubmitted as there were too many conflicts in the old version.
=> Working on #2972 Template Conversion to Twig Format (multipage)

inc/views/base/showteam/showteam.twig, showteam.php
#2972 for the forum team page (showteam.php)
Resubmitted as there were too many conflicts in the old version.
=> Working on #2972 Template Conversion to Twig Format (showteam.php)

inc/functions_post.php, inc/views/base/moderation/getip.twig, inc/views/base/moderation/getip_modal.twig, inc/views/base/moderation/getpmip.twig, inc/views/base/moderation/getpmip_modal.twig, inc/views/base/postbit/postbit.twig, moderation.php
#2972 for the moderation.php IP Address templates.
Also fixes a minor issue with IP addresses on the postbit.
=> Working on #2972 Template Conversion to Twig Format (IP Addresses)

editpost.php, inc/languages/english/global.lang.php, newreply.php, newthread.php
#3044
Should be fine, please review it :)
=> Fixes #3044

polls.php
=> Fixes #3080 view polls for unapproved threads

private.php
=> Fixes #3091 - error if a draft has no recepients

install/resources/mybb_theme.xml
=> Fixes #2970 - Reputation wordwrap

inc/functions.php
=> Fixes #3014 - Signatures in PMs

inc/class_stopforumspamchecker.php
https://github.com/mybb/mybb/issues/2910
=> Fixes #2910 StopForumSpam Confidence level correction

inc/functions.php, inc/views/base/member/register.twig, inc/views/base/member/register_agreement.twig, inc/views/base/member/register_coppa.twig, member.php
#2972 for member registration (member.php?action=register)
I wasn't sure how to handle all the inline $validator_javascript, so I left it.
Resubmitted as there were too many conflicts in the old version.
=> Working on #2972 Template Conversion to Twig Format (member register)

inc/views/base/usercp/profile.twig, inc/views/base/usercp/profilefield.twig, usercp.php
=> Working on #2972 Template Conversion to Twig Format (usercp_profile)

global.php
This PR fixes #3026 adding a check for the `joinable` property in every leader's usergroup.
=> Fixes #3026 – Added joinable check for group leaders

inc/views/base/showthread/inlinemoderation.twig, inc/views/base/showthread/showthread.twig, showthread.php
#2972 for the thread page (showthread.php)
Also (hopefully) fixes #2117 
Resubmitted as there were too many conflicts in the old version.
=> Working on #2972 Template Conversion to Twig Format (showthread.php)

install/resources/mybb_theme.xml
Template version update
Attempt to fix: https://github.com/mybb/mybb/issues/3034
=> Fixes #3034 usercp2.php removal extended - Template version update

admin/modules/config/settings.php
As per comment of @JordanMussi and @Sama34 
Proposing micro fix for handling issue https://github.com/mybb/mybb/issues/3073 for now since the ACP is planned to be rewritten.
=> Fixes #3073 ACP Desc HTML Strip (micro fix)

.gitignore
=> .gitignore enhancement

inc/class_parser.php, jscripts/bbcodes_sceditor.js
This fixes: https://github.com/mybb/mybb/issues/3075
- Fixed broken preview in editor
- Added support for short url
=> Fixes #3075 Support for DailyMotion short URL video embeds

inc/functions_search.php
"Hard Limit for Maximum Search Results" settings implemented.
Attempt to fix: https://github.com/mybb/mybb/issues/3097
=> Fixes #3097 PM Search & Hard Limit

inc/languages/english/usercp.lang.php, install/resources/mybb_theme.xml, usercp.php
As per comment of @labrocca
https://github.com/mybb/mybb/issues/3112#issuecomment-382595690
=> Join Group Reason Limit

inc/functions_modcp.php, inc/views/base/modcp/announcements.twig, inc/views/base/modcp/announcements/forum.twig, inc/views/base/modcp/announcements_add.twig, inc/views/base/modcp/announcements_delete.twig, inc/views/base/modcp/announcements_edit.twig, modcp.php
=> Working on #2972 Template Conversion to Twig Format (modcp announcements)

install/resources/mybb_theme.xml
As per the changes committed in this PR:
https://github.com/mybb/mybb/pull/3110
All affected template's version updated.
=> Fixes #1790 Collapse state alt / title fix - Extended - Template versions update

inc/class_parser.php
Aims to fix the issues raised in the comments of #2968.
Supersedes #3103.
=> Moves automatic URL replacement to the end of parsing.

inc/functions_search.php, inc/views/base/search/results_posts.twig, inc/views/base/search/results_posts_row.twig, inc/views/base/search/results_threads.twig, inc/views/base/search/results_threads_row.twig, inc/views/base/search/search.twig, search.php
#2972 for the search system (search.php & functions_search.php)
=> Working on #2972 Template Conversion to Twig Format (search.php)

install/resources/mybb_theme.xml, memberlist.php
=> Fixes #3176 memberlist_search doesn't check for referral option disabled or enabled

showthread.php
Fixes #3148 Threads table empty data and update_first_post()
=> Fixes #3148 Threads table empty data and update_first_post()

newreply.php
Attempt to fix: #1469 
Adapting simplest possible solution for now: Skip soft deleted posts from duplicate check.
=> Fixes #1469 Soft deleted content is checked for duplicate content.

admin/inc/functions.php, contact.php, install/resources/mybb_theme.xml, member.php, modcp.php, moderation.php, private.php, reputation.php
Attempt to fix #3124 $mybb->input usage drop in template.
To Do:
Template: member_register_coppa
Template: modcp_editprofile
`$modpost_time`
Template: modcp_editprofile_signature
Template: modcp_finduser
Template: modcp_warninglogs
Template: moderation_delayedmoderation_merge
Template: moderation_delayedmoderation_move
Template: moderation_confirmation
Template: moderation_purgespammer
Template: private_move
Template: reputation_add
Template: reputation_add_delete
Template: contact
=> Fixes #3124 XSS and $mybb->input in Templates

inc/datahandlers/pm.php
=> Fixes #3186 Save PM as Draft issue

index.php, portal.php
=> Fixes #2632 begin with bots

search.php
=> Fixes #3173 search forum filtering

forumdisplay.php
Attempt to fix #1890 
Forumdisplay Pagination Count Rectification
=> Fixes #1890 Sort threads by prefix bug

global.php, inc/class_parser.php, inc/views/base/parser/video.twig
=> Working on #2972 Template Conversion to Twig Format (video)

inc/views/base/usercp/usergroups.twig, usercp.php
Please note that `{{ trow }}` doesn't refer to anything at the moment, waiting for a proper Twig function to be implemented.
=> Working on #2972 Template Conversion to Twig Format (usercp usergroups)

.travis.yml
THis shouldn't be merged until we know it works - eg: give Travis a chance to run
=> Adding PHP lint step to before_script for travis

admin/inc/functions_themes.php, admin/modules/style/themes.php
=> Fixes #299 Unwanted CSS Path Modifier Removal

inc/views/base/usercp/attachments.twig, inc/views/base/usercp/attachments/row.twig, showthread.php, usercp.php
Also fixes an issue in showthread with a missing ).
Also fixes the query used to get the attachments to ensure it works on PostgreSQL for @kawaii 😉
=> Convert user CP atatchments page to Twig

inc/views/base/reputation/add.twig, inc/views/base/reputation/add_error.twig, inc/views/base/reputation/add_error_nomodal.twig, inc/views/base/reputation/added.twig, inc/views/base/reputation/deleted.twig, inc/views/base/reputation/reputation.twig, inc/views/base/reputation/reputation_vote.twig, reputation.php
#2972 for the reputation system (reputation.php)
=> Working on #2972 Template Conversion to Twig Format (reputation.php)

inc/languages/english/modcp.lang.php, inc/views/base/modcp/iplookup.twig, inc/views/base/modcp/iplookup_modal.twig, inc/views/base/modcp/ipsearch.twig, modcp.php
#2972 for the IP Search and IP Lookup section of the Mod CP.
Also added a few things to the IP Lookup page (added error message if no IP entered, added a full page for javascript disabled users).
=> Working on #2972 Template Conversion to Twig Format (modcp_ipsearch)

admin/modules/style/themes.php, inc/languages/english/admin/style_themes.lang.php
Attempt to fix #2094 
Validation added to catch invalid color naming pattern.
=> Fixes #2094 Smart bug in color name

inc/class_parser.php
=> Fixes #3128 Extra </li> in lists output by the parser

admin/modules/config/badwords.php, inc/class_parser.php, inc/languages/english/admin/config_badwords.lang.php, install/resources/mysql_db_tables.php, install/resources/pgsql_db_tables.php, install/resources/sqlite_db_tables.php, install/resources/upgrade43.php
Fix #2225 wordfilter cannot replace strings with * in them
=> Fix #2225 wordfilter cannot replace strings with * in them

calendar.php, inc/class_session.php, inc/functions_post.php, install/resources/mybb_theme.xml, member.php, memberlist.php, modcp.php, reputation.php
Fixes #3175 PM Postbit
I tried to update the code so for it to be more consistent.
=> Fixes #3175 PM Postbit

polls.php
Converts $numvotes to integer. Tested with PHP 7.1.
=> Fixes #3228 PHP 7 Compatibility

inc/datahandlers/pm.php, inc/datahandlers/post.php, inc/languages/english/datahandler_pm.lang.php
Attempt to fix #3170 
SQL text field length limit check for posts & PMs
=> Fixes #3170 MySQL error with strict mode if message too long

inc/functions_serverstats.php
Attempt to fix #2445 
host details fetching drop
=> Fixes #2445 Host check code doesn't work anymore

inc/functions.php, install/resources/mybb_theme.xml
Attempt to fix #3169 
lang multipage var separation
=> Fixes #3169 Private.php > Tracking Pagination Issue

editpost.php, inc/functions.php, inc/views/base/error/error.twig, inc/views/base/error/inline.twig, inc/views/base/error/no_permission.twig
Templates not used by MyBB and marked to deletion:
=> Working on #2972 Template Conversion to Twig Format (error)

global.php, inc/views/base/layouts/master.twig
=> Working on #2972 Template Conversion to Twig Format (headerinclude)

inc/functions_modcp.php, inc/views/base/announcements/announcements.twig, inc/views/base/modcp/announcements.twig, inc/views/base/modcp/announcements/forum.twig, inc/views/base/modcp/announcements_add.twig, modcp.php
This PR fixes some issues with announcements which weren't converted properly in my previous PR, such as alt_trow and announcement preview.
=> Adjustments for announcements (#2972)

inc/views/base/modcp/finduser.twig, modcp.php
=> Working on #2972 Template Conversion to Twig Format (modcp finduser)

inc/views/base/xmlhttp/buddyselect.twig, xmlhttp.php
=> Working on #2972 Template Conversion to Twig Format (xmlhttp)

inc/functions.php, inc/views/base/misc/forumjump.twig, inc/views/base/misc/forumjump_bit.twig
=> Working on #2972 Template Conversion to Twig Format (forumjump)

inc/functions.php, inc/views/base/smilieinsert/main.twig
Note that #3249 must be merged for this to be tested properly as it uses a template created there.
=> Working on #2972 Template Conversion to Twig Format (smilieinsert)

global.php, inc/functions.php, inc/views/base/partials/footer.twig
Note that this also includes `task_image` in the footer template, but its conversion will be handled separately.
=> Working on #2972 Template Conversion to Twig Format (footer)

inc/views/base/modcp/allreports.twig, inc/views/base/modcp/allreports/item.twig, inc/views/base/modcp/reports.twig, inc/views/base/modcp/reports/item.twig, modcp.php
#2972 for the report center section of the Mod CP.
=> Working on #2972 Template Conversion to Twig Format (modcp_reports)

inc/views/base/modcp/banning.twig, inc/views/base/modcp/banuser.twig, modcp.php
#2972 for the banning and ban user pages of the Mod CP
=> Working on #2972 Template Conversion to Twig Format (modcp_banning)

inc/src/Twig/Extensions/LangExtension.php
`$lang->parse` replacement #2976
=> For #2976 — $lang->parse()

inc/views/base/modcp/modqueue/attachment.twig, inc/views/base/modcp/modqueue/post.twig, inc/views/base/modcp/modqueue/thread.twig, inc/views/base/modcp/modqueue_attachments.twig, inc/views/base/modcp/modqueue_empty.twig, inc/views/base/modcp/modqueue_posts.twig, inc/views/base/modcp/modqueue_threads.twig, modcp.php
#2972 for the Mod Queue sections of the Mod CP.
=> Working on #2972 Template Conversion to Twig Format (modcp_modqueue)

global.php, inc/languages/english/global.lang.php, inc/src/Twig/Extensions/ThemeExtension.php, inc/views/base/messages/banneduser.twig, inc/views/base/messages/base.twig, inc/views/base/messages/boardclosed_reason.twig, inc/views/base/messages/dst_detection.twig, inc/views/base/messages/pmnotice.twig, inc/views/base/modals/base.twig, inc/views/base/modals/boardclosed.twig, inc/views/base/modals/no_permission.twig, inc/views/base/partials/header.twig
Templates orphaned which seem to have been discarded or already converted with other PRs:
- global_moderation_notice
=> Working on #2972 Template Conversion to Twig Format (global)

inc/views/base/modcp/editprofile.twig, modcp.php
Marked as TODO:
- my_date() over a bunch of dates
=> Working on #2972 Template Conversion to Twig Format (modcp editprofile)

inc/functions_post.php, inc/languages/english/private.lang.php, inc/views/base/postbit/postbit.twig, inc/views/base/private/advanced_search.twig, inc/views/base/private/empty.twig, inc/views/base/private/export.twig, inc/views/base/private/export/csv.twig, inc/views/base/private/export/html.twig, inc/views/base/private/export/txt.twig, inc/views/base/private/folders.twig, inc/views/base/private/private.twig, inc/views/base/private/private/item.twig, inc/views/base/private/read.twig, inc/views/base/private/results.twig, inc/views/base/private/results/item.twig, inc/views/base/private/send.twig, inc/views/base/private/tracking.twig, private.php
#2972 for the private message system (private.php).
=> Working on #2972 Template Conversion to Twig Format (private.php)

inc/views/base/usercp/home.twig, usercp.php
Hooks dropped:
- usercp_notepad_start
- usercp_notepad_end
=> Working on #2972 Template Conversion to Twig Format (usercp)

inc/views/base/index/index.twig, inc/views/base/usercp/draft_row.twig, inc/views/base/usercp/subscribed_forum_row.twig, inc/views/base/usercp/subscribed_thread_row.twig, index.php
Working on #2972, converting index templates. My first conversion, hope everything's correct.
=> Working on #2972 Template Conversion to Twig Format (index)

forumdisplay.php, inc/functions.php, inc/views/base/forumdisplay/forumdisplay.twig, inc/views/base/forumdisplay/inlinemoderation.twig, inc/views/base/forumdisplay/password.twig, inc/views/base/forumdisplay/thread.twig, inc/views/base/forumdisplay/thread_deleted.twig, inc/views/base/forumdisplay/thread_modbit.twig, inc/views/base/forumdisplay/thread_rating.twig
=> Working on #2972 Template Conversion to Twig Format (forumdisplay)

install/resources/settings.xml
=> Forum Team Settings Disporder

inc/datahandlers/user.php
=> Away reason error variable name

jscripts/inline_moderation.js
=> Fixes #3241 .prop('checked') doesn't trigger change events

jscripts/general.js
Now toggles classes, hiding and showing should be done via CSS. For #3282
=> Update Collapse for Javascript Updates #3282

install/resources/mybb_theme.xml
Template version updated left in this PR
https://github.com/mybb/mybb/pull/3227/files
=> Missed out template version update in 1.8.16

install/resources/upgrade43.php
This PR fixes a reported issue upgrading to 1.8.16 with certain settings turned on.
=> Fixed missing parentheses

index.php, portal.php
https://community.mybb.com/thread-218429.html
=> Strange comma in whosonline

report.php
Resolved undefined permission
https://community.mybb.com/thread-218439.html
=> Fix Unable to Report in 1.8.16

inc/languages/english/index.lang.php, index.php, install/resources/mybb_theme.xml
Fixes #3304 The separator is moved into a language variable and the templates including the separator are updated.
=> Fix #3304 - conditional sepator

install/resources/mybb_theme.xml, jscripts/general.js
Fixes #3310 by updating CSS classes inside `general.js`.
=> Fixes #3310 - update general.js

install/resources/mybb_theme.xml
=> Fixes #3321 by updating CSS class

install/resources/mybb_theme.xml
Fixes #3323 - recreated as the old PR got broke when I rebased on upstream...
=> Add missing post key

install/resources/mybb_theme.xml
Bump template version to 1817 for already merged PRs - #3302 (issue #3308) and #3301 (issue #3311)
=> Bump template version to 1817 for merged PRs

jscripts/general.js
Was missing children selector for click event. #3283
=> Collapse fix

CONTRIBUTING.md
Update Contributing to reflect new bug reporting policy
=> Update Contributing to new policy

inc/functions.php
Attempt to fix #3337 
Guest group permission fix
=> Fixes #3337 Unable to retrieve guest permissions while logged in

admin/inc/class_page.php
Fixes #2540 
Replace php_self with script_name
=> Fixes #2540 Issue with adminCP login page and redirection

install/resources/mybb_theme.xml
Attempt to fix #3349 
Unnecessary variable removal from templates
=> Fixes #3349 Unnecessary variable removal from templates

admin/modules/config/badwords.php, inc/languages/english/admin/config_badwords.lang.php
Attempt to fix #3354 
Badword regex validation implementation.
=> Fixes #3354 Invalid regular expression in Bad words filter throwing PHP warning

showteam.php
Attempt to fix #3363 
Added 'sqlite' compatibility in query part.
=> Fixes #3363 SQLite ShowTeam Error

admin/modules/user/users.php, install/resources/mybb_theme.xml, jscripts/inline_moderation.js
=> Trigger event on selectall change

install/resources/mybb_theme.xml, member.php
Fixes #3295 by adding a captcha to lost password request page.
=> Fixes #3295 Reset password should have captcha or require username too.

inc/functions.php, newreply.php, newthread.php
Attempt to fix #3341 
Subscription bug while reply
- Fixed subscription assignment on quickreply action
- Created `get_subscription_method()` function, optimized code.
=> Fixes #3341 Thread Subscription Bug

install/resources/mybb_theme.xml, private.php, xmlhttp.php
Attempt to fix #2659 
Duplicate PM Receipient Fix
=> Fixes #2659 Double recipients with private messages

inc/class_parser.php, inc/datahandlers/user.php
Attempt to fix #3144 
Signature length count considering only visible characters
After several discussions and [attempts](https://github.com/mybb/mybb/pull/3179) I have come up with this simplest solution to consider only visible characters to take in account while counting. Tested and the counts appearing as desired.
=> Fixes #3144 MyCode affects signature length Issue

forumdisplay.php, inc/views/base/forumdisplay/forumdisplay.twig, inc/views/base/forumdisplay/thread.twig
For #2972. This PR fixes a lot of issues due to a partial conversion likely originated from a corrupted/wrong rebase and conflicts fix.
Note that some things are marked as TODO in Twig comments (mainly `get_thread_link` lacking from Twig functions).
=> Fixed partial rebase issue with forumdisplay

inc/datahandlers/post.php, inc/functions.php
=> Fixes #3368 Syntax error in MyBB 1.8.17

install/resources/mysql_db_tables.php, install/resources/pgsql_db_tables.php, install/resources/sqlite_db_tables.php
=> Fixes custom profile fields on install

attachment.php
Fixed #3287 by checking if the post has been saved as draft.
I only added 1 condition, git thinks I changed all lines...
=> Fixes #3287 Unable to view or add attachments if new post was saved as draft before posting

install/resources/mybb_theme.xml
=> Fixes #3378 - Add a check box "remember_me"

inc/functions.php, inc/views/base/forumdisplay/threadlist_prefixes.twig, inc/views/base/postbit/reputation.twig, inc/views/base/postbit/warninglevel.twig
For #2972. This PR converts the last pieces left behind the granular conversion we performed back in the days for inc/functions.php.
=> Working on #2972 – inc/functions.php cleanup

inc/class_parser.php
Main Issue:
https://github.com/mybb/mybb/issues/3262
Subsequent Pull Request:
https://github.com/mybb/mybb/pull/3353
Recognized Refinement Requirements:
https://github.com/mybb/mybb/pull/3353#discussion_r210769365
https://github.com/mybb/mybb/pull/3353#discussion_r210769229
=> Bad word filter - extended refinement

inc/class_plugins.php
Also modifies the doc to use the callable type and adds scalar type hints throughout.
Fixes a bug in `remove_hook` where the method representation for callbacks with objects were using `get_class` rather than `spl_object_hash`.
=> Add support for \Closure type hooks.

install/resources/language.lang.php
=> Fixes #3393 - Grammar issue in upgrade script

install/resources/mybb_theme.xml
=> Fixes #3412 - Inconsistent Styling of Restore Button

misc.php
=> Fixes #3429 Smilies issue with 1.8.18 upgrade

install/index.php, install/resources/pgsql_db_inserts.php
=> Fix #3428 Missing database inserts for engines other than MySQL

install/resources/mybb_theme.xml, member.php
=> Fixes #3436 Resend email verification missing captcha

usercp.php
=> Fixes #3457 - User CP - lock to close icon

admin/modules/home/index.php
=> Fixes #3443 MyBB ACP - Latest announcements scraping wrong and repeated content

usercp.php
=> Fixes #3403 - New plugin hooks in user CP

install/resources/mybb_theme.xml
Fixes #3291 Replaces {$thread['threadprefix']} with {$thread['displayprefix']} to add style to the prefixes in showthread
=> Fixes #3291 - Issue with Thread Prefix

managegroup.php
Fixes #3468 as described [here](https://community.mybb.com/thread-220212-post-1316567.html#pid1316567).
=> Fix #3468 per page in manage group

index.php
=> Fix #3473 - Add index_showteamlink to templatelist

inc/class_error.php
=> Fix #3477 - Include back trace in error logs and error emails

inc/languages/english/memberlist.lang.php, install/resources/mybb_theme.xml, memberlist.php
=> Fixes #3483 Add 'exact' option to memberlist username search

inc/src/Application.php
Correct the references to Laravels base path in the docblocks.
=> Correct Laravel references

inc/views/base/stats/stats.twig, stats.php
=> #2972 (stats.php) forum statistics to twig

inc/views/base/showteam/showteam.twig, showteam.php
Adds avatars to the forum team page as discussed in Discord.
=> Add avatars to forum team

modcp.php
Attempt to fix #3504 
Corrected typo in variable name
=> Fixes #3504 ModCP warninglogs pagination issue

admin/modules/user/users.php
Attempt to fix #2020 
- Referrer / Referrals carry over
- Undefined / Same user error logic fine tuning
- Slight code optimization
Note: Addressing only the titled issue for now. If the extended part as mentioned in comments (related to reputation, not referrals) are also required that can be done too ...
=> Fixes #2020 Referrals Are Lost on Account Merge

member.php
=> Fixes #3538 Member Profiles have Send Email link

install/resources/mybb_theme.xml
=> Fixes #3533 - UCP - alignment in forum sub.

inc/functions_user.php, inc/languages/english/global.lang.php, install/resources/mybb_theme.xml, private.php
=> Fixes #3514 Show only unread private messages

editpost.php, newreply.php, newthread.php
=> Add check for ajax in newthread and newreply

global.php
#3553 
@effone kindly asked me due to his personal reasons to create this PR to fix this issue, all credits go to @effone
=> Fixes #3553 - Mod notice - lang typo

install/resources/mybb_theme.xml, modcp.php
Fixes #3578 
Adds `fixed` to the wrapper `<table>` as is used in `shortbread.php` and adds message parsing based on forum settings.
=> Fix #3578 mod cp threads approval

install/resources/mybb_theme.xml
Attempt to fix #3583 
Added width option.
=> Fixes #3583 MyBB 1.8.20 Editor Is Too Small

admin/modules/config/report_reasons.php
=> Fixes #3601 - report reasons caching

index.php
=> Fixes #3596 separator on index page

global.php
=> Fixes #3587 - mod notice templates are not cached

private.php
=> Fixes #3598 1.8.20 - unread PMs - pagination

inc/class_stopforumspamchecker.php
=> Fixes #3604 - Stopforumspam new URL for API call

install/resources/mybb_theme.xml
=> Fixes #3613 - select2 clear in memberlist

inc/languages/english/admin/config_settings.lang.php
=> Fixes #3608 - Match error log with MyBB docs

modcp.php
Attempt to fix #3590 
Need to confirm few other existences though ...
=> Fixes #3590 Empty index operator

install/resources/mybb_theme.xml
=> Fixes #3520 Invisible Recaptcha - PW Reset Error

inc/languages/english/admin/config_attachment_types.lang.php
Fixes #3610 
If you have a better description in your mind, let me know :)
=> Fixes #3610 - Disabling extensions - better description

global.php
=> Fixes #3636 - JS error in modal templates

newreply.php, newthread.php
=> Fixes #3614 Posting Limits and Post Moderation

admin/modules/user/users.php
=> Fixes #3627 - format_avatar remote avatars

private.php
https://community.mybb.com/thread-222444.html
Fixes #3634
=> Fixes #3634 empty folders counters

admin/modules/config/questions.php, inc/languages/english/admin/config_questions.lang.php, jscripts/question.js, member.php, xmlhttp.php
Added parser for security questions at lines 1221 to 1237.
Still possible that 200 characters for security questions may be too short when mycode formatting is used.
=> fix #3383 - unable to add images to register questions

inc/functions_calendar.php
=> Fixes #3625 - PHP 7 compatibility for functions_calendar.php

xmlhttp.php
=> Fixes #3657 Missing CSS-class in referral modal

inc/functions_search.php
=> Fixes #3609 - Fulltext search and stopwords

private.php
=> Fix #3676 - SQL Error When Viewing Unread PMs

private.php
Attempt to fix #3666 
Search result folder reset
=> Fixes #3666 PM search - incorrect folder

admin/modules/style/themes.php, inc/languages/english/admin/style_themes.lang.php
Attempt to fix #3611 
Theme Access Reset on Force
=> Fix #3611 Change Usergroup & Hidden Theme Interfering

inc/class_feedgeneration.php, inc/languages/english/misc.lang.php, install/resources/mybb_theme.xml, misc.php, syndication.php
Attempt to fix: #3681 
Reference: https://community.mybb.com/thread-221222.html
This supersedes PR #3528 
Tasks:
=> Syndication

global.php, inc/functions_post.php, install/resources/mybb_theme.xml, jscripts/general.js, member.php, usercp.php
Second phase attempt to fix #3540
_(finger crossed)_
=> Fixes #3540 Omit unwanted links / buttons (v.2)

jscripts/bbcodes_sceditor.js
Attempt to fix #3691 
Point to DOM node instead of jQuery object
=> Fix #3691 Quote disappears in source mode

jscripts/bbcodes_sceditor.js
Attempt to fix #3693 
insert correction
=> Fix #3693 email insert doesn't work in source mode

global.php
=> Fixes #3696 - header_welcomeblock_member_buddy template cache

install/resources/mybb_theme.xml, usercp.php
=> Fixes #3718 Uncaught Error when changing usernames

modcp.php
Attempt to fix #3713
error check correction
=> Fix #3713 Moderator notes fail to get saved

admin/inc/functions.php, admin/modules/forum/management.php, admin/modules/tools/recount_rebuild.php
This should fix #3707, but I haven't tested it yet.
=> Fix #3707 - "&hellip;" is displayed in redirect button

jscripts/bbcodes_sceditor.js
=> Fixed #3725 - vimeo bbcode

inc/db_pgsql.php
=> Fix #3723 PostgreSQL `LIMIT` correction code

inc/views/base/forumdisplay/thread.twig
Found a small error while setting up a mybb 1.9 test platform
=> Fixed error in thread.twig

warnings.php
=> Fixes #3741 Warn User doesn't carry over Expiry

memberlist.php
=> Resolve #3746 Last Visit of hidden users disclosed through display order on Member List

admin/modules/forum/moderation_queue.php
=> Fix-3672 Long text breaks page formatting in ACP moderation queue

admin/modules/forum/management.php, admin/modules/user/groups.php
=> Fixes #3739 - replace hard coded values in ACP

admin/modules/home/preferences.php
=> Fixes #3742 - ACP Home/Preferences code improvements

inc/tasks/delayedmoderation.php
=> Fix #3665 - use `continue 2;`

global.php
=> #3722 - use `INNER JOIN` to get poll rather than `LEFT JOIN`

modcp.php
=> Fix #3736 Moderator options on Profile Management fail to get saved

inc/functions_post.php, member.php, report.php, reputation.php, showthread.php
=> Fix #3709 Report button appearance / availability improvement

admin/modules/user/users.php, inc/datahandlers/user.php, member.php, memberlist.php
=> Fix #3669 User Last Visit / Active accuracy

install/resources/mybb_theme.xml, jscripts/post.js, jscripts/thread.js
A quick fix for #3773, detail goes [this thread](https://community.mybb.com/thread-224271.html).
=> Fix #3773 quoting post from other threads not working.

inc/functions.php
It's a quick fix that should be working.
BTW, seems it's conventional in MyBB to use `#` as the delimiter for PCRE functions, but some outliers use `/`. I'm not sure so I didn't change it.
Source: [community post](https://community.mybb.com/thread-224406.html)
=> Fix enforced case sensitivity check on HEADER's location field

composer.json, composer.lock
=> Fix #3798 - update Twig to v2.11.

install/resources/upgrade49.php
`upgrade49.php` for 1.8.22 upgrade script.
=> Add missing header output in 1.8.22 upgrade script.

.travis.yml, composer.lock, inc/class_parser.php, inc/src/Application.php, inc/src/Plugins/HookManager.php, inc/src/Plugins/ServiceProvider.php, inc/src/Twig/Extensions/CoreExtension.php, inc/src/Twig/Extensions/LangExtension.php, inc/src/Twig/Extensions/ThemeExtension.php, inc/src/Twig/Extensions/UrlExtension.php, inc/src/Twig/ServiceProvider.php, inc/src/functions.php, tests/Unit/ParserTest.php, tests/Unit/Plugins/HookManagerTest.php
Fixed #3594 - allow hooks with multiple arguments. Allow closure hooks.
In the future, the old `pluginSystem` class will be updated to proxy to `Mybb\Plugins\HookManager` - I just need to work out the best approach to that.
=> Fix 3594 - new plugin system hook manager to allow multiple arguments

forumdisplay.php
A new hook I need in forumdisplay.php.
=> New plugin hook for forumdisplay.php (as mentioned in #3724)

inc/tasks/promotions.php
=> Time Online logic correction in group promotion

inc/class_parser.php
=> Resolves #3813 Counter correction

inc/languages/english/global.lang.php
=> Fixes #3702 - Case sensitivity in English

install/resources/mybb_theme.xml, search.php
=> Fix #3806 - allow do_search to be GET or POST

report.php
=> Fix for #3825

inc/datahandlers/login.php
Related to #3762, extends #3769
=> Prevent sessions from being deleted on login

inc/class_parser.php
=> Revert "Resolves #3813 Counter correction"

install/resources/upgrade12.php, install/resources/upgrade13.php, install/resources/upgrade17.php, install/resources/upgrade30.php, install/resources/upgrade35.php
=> Resolve #3841 JavaScript auto-submit broken during upgrade

global.php
=> Fixes #3818

jscripts/bbcodes_sceditor.js
=> Resolve #3848 Invalid list code inserted in text mode in SCEditor

inc/languages/english/datahandler_warnings.lang.php
=> Fixes #3856 - Quotes in lang file

forumdisplay.php
=> Fixes #3724 - Forumdisplay hook

install/resources/mybb_theme.xml
=> Fixes #3862 - header_welcomeblock_guest_login_modal

inc/functions.php
=> Fixes #3646 - hook -> copy_file_to_cdn_start

online.php
=> #3874: SQL Error when sorting by username in online.php

admin/modules/config/report_reasons.php
=> Fixes #3897 - Fatal error in report_reasons.php

admin/modules/user/banning.php, admin/modules/user/groups.php, admin/modules/user/users.php, global.php, inc/class_datacache.php, inc/class_session.php, inc/datahandlers/user.php, install/index.php, install/resources/upgrade50.php, install/upgrade.php, modcp.php, moderation.php
=> Resolve #3878 Remove "banned" datacache

admin/modules/forum/management.php
=> Fixes #3938 SQL error when copying a category without parent

inc/class_session.php
=> Remove IP check from session::init()

admin/modules/user/users.php
=> ACP Username Visibility

install/resources/mybb_theme.xml
=> Fixes #3915 - Invisible reCAPTCHA - resend email page

admin/modules/forum/management.php
This should be fine, but it depends on your resolution...
Resolves #3890
=> Fixes #3890 - Forum order - make it wider

admin/inc/class_page.php, admin/inc/functions_themes.php, admin/modules/user/users.php, inc/class_moderation.php, inc/datahandlers/user.php, inc/functions_upload.php, install/resources/upgrade12.php, install/resources/upgrade30.php
Fixes Missing globals/variables and duplicate array_keys
Signed-off-by: Jonathan <vbgamer45@gmail.com>
Resolves #3943
=> Fixes Missing globals/variables and duplicate array_keys

admin/modules/forum/attachments.php
=> Fix #3757 attachment paging links missing forum info in AdminCP

inc/languages/english/global.lang.php
Language variable was missed in #613.
Resolves #3953
=> Fixes #3953 Undefined language variable

inc/languages/english/member.lang.php, member.php
=> Fix #3909 Referrals by a user doesn't check the user's existence

inc/cachehandlers/redis.php, inc/class_core.php, inc/class_datacache.php, install/index.php
=> Fix #3957 add Redis support

member.php
Resolves #3572
Untested, please review.
@Ben-MyBB @Sama34
=> Fixes #3572 - Resend email activation

inc/functions.php, install/resources/settings.xml, install/resources/upgrade50.php
=> Send `Cache-Control: no-cache, private` header by default

search.php
=> Resolves #3973

install/resources/mybb_theme.xml
=> Remove unnecessary name tag from announcement templates

inc/db_pgsql.php
=> Improve query match pattern in DB_PgSQL::insert_id()

forumdisplay.php, install/resources/mybb_theme.xml
Replaces PR #3891 at @Eldenroot's request.
=> Adds thread start datetime to thread listings in forumdisplay.php.

index.php
=> Fix spider double counting, use separate query for global guest count on forum index

admin/modules/user/users.php, install/resources/mybb_theme.xml, jscripts/bbcodes_sceditor.js
=> Fix non-supported video code breaking SCEditor

admin/modules/user/admin_permissions.php, inc/languages/english/admin/user_admin_permissions.lang.php
=> Fixes #3997 - missing lang phrase

inc/cachehandlers/apcu.php, inc/class_core.php, inc/class_datacache.php, install/index.php
This PR implements an APCu based cache handler. This has been tested locally.
Resolves #3988
=> Add APCu cache handler

install/resources/mybb_theme.xml
=> Fixes #3866 - Allow clear select2 box

inc/class_error.php
=> Improve generate_backtrace() and use for error logs

inc/functions_online.php, inc/languages/english/misc.lang.php, inc/languages/english/online.lang.php, install/resources/mybb_theme.xml, misc.php
Resolves #3865 
Removes the last bit of the IM Center
=> Fixes #3865 misc_imcenter_skype

install/resources/mybb_theme.xml
=> Fixes #3990 - Invisible Captcha is broken sendthread

report.php
=> Fixes #4009 wrong forum password check in `report.php`

install/resources/mybb_theme.xml
Signed-off-by: effone <me@eff.one>
Resolves #4018
=> Jump Page Input Type Correction

install/resources/mybb_theme.xml
@Eldenroot can you check if this is what you require?
Resolves #3971
=> Resolves #3971 - Add "lazy loading" for mycodes

calendar.php, install/resources/mybb_theme.xml
Marking this as a draft for now until I have had a look at the upgrade script and throughly tested this, but I wanted to open this for feedback on my method. An inital start on resolving #3771. Upgrade script still needs to be considered before merging to insert the additional two templates required.
All feedback is welcomed since I am still learning PHP :)
Resolves #3771
=> Resolves #3771 - Seperate variables for calendar.php

admin/modules/home/preferences.php
=> Fixes #2011 Wrong theme shown as selected in ACP preferences

install/resources/mybb_theme.xml
Oversight of when there is no limit (max = 0)
My mistake sorry @euantorano !
=> Continues #4038 Change max recipients

inc/class_parser.php, search.php
=> Fixes #4044 Attachment code isn't stripped off post previews

usercp.php
=> Resolves #1803 - Disabled MyCode SCEeditor inconsistency

admin/modules/user/users.php
Resolves #4036
See https://github.com/mybb/mybb/issues/2020#issuecomment-636474793
=> Fixes #4036 Referrals not transferred correctly when merging users

usercp.php
Resolves #3851 + optimization that may most of the time save a query
=> Fix #3851 User CP -> pagination in Attachments is broken

editpost.php
Just putting the fix provided into a PR (https://github.com/mybb/mybb/issues/3020#issuecomment-363634545)
Resolves #3020
=> Resolves #3020 - Delete post checkbox and settings

install/resources/mybb_theme.xml
=> Resolves #4027 - Editor error with quote

admin/index.php
Resolves #4045 by reverting #2783 (the original fix for #2700) and fixing in a different way.
=> Fixes #4045 AdminCP style override login

inc/languages/english/private.lang.php, install/resources/upgrade50.php, private.php
Signed-off-by: effone <me@eff.one>
Resolves #3733
=> Fixes #3733 PMs lost when moved to Inbox
